### ISSUE TITLE
`∷` (parity) does not work on decimals

### ISSUE THREAD

**Issue by Steffan153** [Vyxal/Vyxal#1029]
`2%` does, though.

**Comment by chunkybanana** [comment]
What specifically should this do on decimals? Should it output 1 only if the number is not divisible by 2?

**Comment by SE-Nitro** [comment]
Maybe round the number first?

**Comment by Steffan153** [comment]
It should act the same as `2%`.

**Comment by SE-Nitro** [comment]
so do nothing?
