### ISSUE TITLE
in the canvas, `^` and `v` patterns create the same output as `<` and `>`

### ISSUE THREAD

**Issue by Steffan153** [Vyxal/Vyxal#1034]
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCJcXDEgNiBcXF4gw7heLFxuYFxcbmAsXG5cXDEgNiBcXHYgw7heLFxuYFxcbmAsXG5cXDEgNiBcXDwgw7heLFxuYFxcbmAsXG5cXDEgNiBcXD4gw7heLCIsIiIsIiJd)

`^` should be equivalent to `[1, 3]` and `v` should be equivalent to `[7, 3, 1]`.

**Comment by chunkybanana** [comment]
My bad lol
