### ISSUE TITLE
Digraphs for creating lists

### ISSUE THREAD

**Issue by cgccuser** [Vyxal/Vyxal#1049]
Here are some digraphs Vyxal could maybe use for creating lists (some might already be implemented and I just didn't see them):
- [ ] Haskell's [unfoldr](https://hackage.haskell.org/package/base-4.16.1.0/docs/Data-List.html#v:unfoldr) and Scala's [unfold](https://scala-lang.org/api/3.x/scala/collection/immutable/Seq$.html#unfold-fffffdbf). This element would be a dyad similar to `Ḟ`. It'd take a monad `f` and an initial state `s`. At every iteration, `f` would be given the previous state and would output either an empty list, ending the list, or a list `[nextState, nextElement]`, in which case `nextElement` would be added to the list and the sequence would continue. Not sure how useful this might be, as this is basically just `Ḟ` followed by a map.
- [x] [Husk](https://github.com/barbuz/Husk/wiki/Commands)'s `iterP`. This is also like `Ḟ`, but at every iteration, the function is given the list of previous values. You start out with `[]` or some user-provided initial vector, or maybe have digraphs for both. This is pretty useful in Husk, at least.
- [ ] Husk's `iterL`. Similar to `iterP`, except the function provided outputs a list of values, and the final list is created by joining the values together. Basically `iterP` followed by `concat`, so idk how useful this is.
- [ ] An element taking a function `f`, an initial element `e`, and the index in the result of `e`. `f` would be a dyad taking an element and its index in the sequence and outputting a list of more elements and their corresponding indices. These element-index pairs would be plugged back into `f` to continue creating the list. Might be hard to implement and not that useful outside of some specific sequence challenges.
- [ ] An element like Husk's `iterP` / `Ḟ`, except you get the next element from only the previous element.

**Comment by Lyxal** [comment]
> [Husk](https://github.com/barbuz/Husk/wiki/Commands)'s iterP. This is also like Ḟ, but at every iteration, the function is given the list of previous values. You start out with [] or some user-provided initial vector, or maybe have digraphs for both. This is pretty useful in Husk, at least.

That's the definition of `Ḟ` lol.

**Comment by cgccuser** [comment]
@Lyxal Oh lol, I thought it was given only the previous value at each iteration. In that case, I'll add another request where it only gets the last value.

**Comment by cgccuser** [comment]
@Lyxal Looks like `iterP` isn't the exact same as `Ḟ`. `iterP` gives the function the list of all previous values, while `Ḟ` only gives it as many previous values as the function can take as arguments.

**Comment by Lyxal** [comment]
Well it was previously the exact same. #1060 made it different.

**Comment by cgccuser** [comment]
@Lyxal Okay, I guess you'd get the same behavior as `iterP` if you used the old `Ḟ` and also used `W` to turn the elements back into a single list.

**Comment by Steffan153** [comment]
Should these be digraphs or monographs?

**Comment by ysthakur** [comment]
Digraphs, probably
