### ISSUE TITLE
Add element to divide list into n parts

### ISSUE THREAD

**Issue by Steffan153** [Vyxal/Vyxal#1062]
We already have `/`, but it only works on strings.

**Comment by SE-Nitro** [comment]
That's `ẇ`. [Try it online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLin6gxfDJ8M3w0fDV8Nnw3fDh8OeKfqTLhuociLCIiLCIiXQ==)

**Comment by SE-Nitro** [comment]
Maybe we could make `/` not vectorize and make it an overload?

**Comment by Steffan153** [comment]
Non-vectorizing could be annoying. Let's just do a digraph
