### ISSUE TITLE
Canvas Element bug

### ISSUE THREAD

**Issue by SE-Nitro** [Vyxal/Vyxal#1063]
I think the canvas element's length is buggy if it wasn't deliberately.
Length 2 should do [this](https://vyxal.pythonanywhere.com/#WyIiLCIiLCJcXCMzXFxbw7heLCIsIiIsIiJd) and not [this](https://vyxal.pythonanywhere.com/#WyIiLCIiLCJcXCMyXFxbw7heLCIsIiIsIiJd).

**Comment by chunkybanana** [comment]
[status-bydesign] - It's drawing lines of length 3. IMO the current behaviour is more useful, but we could change it.
