### ISSUE TITLE
Add string interpolation

### ISSUE THREAD

**Issue by Steffan153** [Vyxal/Vyxal#1073]
Basically we need to find a character that's not yet used by the short dictionary, and every time it is used in a string, it will pop from the stack and interpolate. (This can be done now, not in v3.)

**Comment by Lyxal** [comment]
Maybe modify the behaviour of `%` in strings to do that?

Currently it only formats if you call `%` on that string.

**Comment by Steffan153** [comment]
I was thinking a Unicode character, like `¥`.
