### ISSUE TITLE
Tool-tip font not showing as monospace on desktop

### ISSUE THREAD

**Issue by Lyxal** [Vyxal/Vyxal#1115]
It renders as Times New Roman (I think) on Vivaldi, Edge and Firefox

## Vivaldi

![image](https://user-images.githubusercontent.com/36217120/174826317-27ad9a03-2dbb-4e08-9417-8f1d04222b67.png)

## Firefox

![image](https://user-images.githubusercontent.com/36217120/174826451-37365ed0-914b-4f23-a1ad-ecb07cc9398f.png)

## Edge

![image](https://user-images.githubusercontent.com/36217120/174826534-4eda257f-4209-4f3c-b4e8-cbd3822d3184.png)

**Comment by Lyxal** [comment]
Quick question: did y'all forget to link DejaVu Sans Mono in the CSS?

**Comment by cgccuser** [comment]
I can reproduce this in Vivaldi and Google Chrome. I don't have DejaVu Sans Mono on my computer either.

**Comment by Lyxal** [comment]
I do not have DejaVu Sans Mono either.

**Comment by cjquines** [comment]
without css styling the tooltip, its font is the browser/system default
