### ISSUE TITLE
Need number overload for `Ṫ` (Tail Remove)

### ISSUE THREAD

**Issue by cgccuser** [Vyxal/Vyxal#1147]
Currently, `Ṫ` has no overload for numbers, so it just removes the last character of the stringified version of the number and converts it to an integer. This is somewhat useful for integers, since it's basically integer division by 10 for them, but I can't see too many use cases for decimals. I think there needs to be a different overload for numbers. Any suggestions?

**Comment by Steffan153** [comment]
I'd say keep it as it is. Dividing by ten can be useful.

**Comment by cgccuser** [comment]
But it's only dividing by ten for integers. For rationals, it's dividing the denominator by ten and then truncating, which is pretty useless. There should be a number overload for `Ṫ` that is somewhat close to the current functionality but actually makes sense for numbers (maybe a proper divide/integer divide by 10).

**Comment by Lyxal** [comment]
What if `if 1 (or truthy) push context variable else push nothing`?

That'd be in scenarios where you've just done a logical comparison and want to conditionally retrieve `n`

**Comment by chunkybanana** [comment]
What about pushing 0 under n, or pushing 1 under n?
(Or pushing [] under n). This could be useful for various reasons, and we have `g` and `G` as well.

**Comment by cjquines** [comment]
you could call that "Truthy Over" and the mnemonic is because it's T with an overdot except it's not actually Over it's Under
