### ISSUE TITLE
Two different implementations of `ÞR`

### ISSUE THREAD

**Issue by cgccuser** [Vyxal/Vyxal#1150]
There are currently two implementations of `ÞR`
1. Remove the last item of the cumulative sums of a list and prepend 0.
2. Reduce the rows of a by function b

I think the second is more general and worth keeping. The first is extremely specific.

(this was mentioned in the big bugs issue (test case `[[]] : [0]`))

**Comment by Steffan153** [comment]
I've used the first before (remove last of cumulative sums and prepend 0). Reduce the rows of a by function b is useless, just vectorised reduce.

**Comment by Lyxal** [comment]
Remove the last item of the cumulative sums of a list and prepend 0 seems like it should be kept because no need to have a digraph for `vƒ`
