### ISSUE TITLE
Add "test cases" to online interpreter

### ISSUE THREAD

**Issue by Steffan153** [Vyxal/Vyxal#1177]
It would basically just run each test case and output it and its result. I would say a format like this:

Test-cases will be separated by a newline. Empty lines are ignored. A test-case would be a comma-separated list of inputs. Spaces around commas are optional.
Optionally, each test case can have an expected output at the end, by adding `=>` or `->` (optional spaces around it) and the expected output, which will make it verify the output.
If a test case ends with a comma, `=>`, or `->`, it should wrap to the next line.

**Comment by chunkybanana** [comment]
Why not have a `t` flag or similar that runs the input as testcases in some format?

**Comment by Steffan153** [comment]
That sounds fine, although we already have `t` and `T` flags.

**Comment by chunkybanana** [comment]
`τ` or `ṫ` then?
