### ISSUE TITLE
`øṘ` doesn't work for values 4000 and above

### ISSUE THREAD

**Issue by Steffan153** [Vyxal/Vyxal#1185]
It should be valid, just add tons of `M`s.

**Comment by cjquines** [comment]
i believe the standard way is to multiply values by 1000 by marking them somehow, see e.g. [this ppcg q](https://codegolf.stackexchange.com/q/797/103205) or [the mathematica function](https://reference.wolfram.com/language/ref/RomanNumeral.html).

**Comment by Steffan153** [comment]
Right, normally overlines are used, but we don't care here. It's currently configured to error when given 4000 or above.
