### ISSUE TITLE
Grouping modifiers are very sus

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#1195]
# [Vyxal](https://github.com/Vyxal/Vyxal), 6 bytes
```
??₍₃₅W
```
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCI/P+KCjeKCg+KChVciLCIiLCIxMDAxIl0=)

The input is pushed twice, and both operations are monads. Yet both values are popped. This is sus

**Comment by Lyxal** [comment]
It's a result of the last time you asked about modifiers in #790.

I'll look into it

**Comment by Lyxal** [comment]
I have an idea on how to fix, but #990 needs to be merged first because I have something that would build on that
