### ISSUE TITLE
Nth generator

### ISSUE THREAD

**Issue by mathcat4** [Vyxal/Vyxal#1210]

**Comment by Steffan153** [comment]
Whoops, didn't mean to close

**Comment by SE-Nitro** [comment]
No, sorry I wasn't clear, this is different:
Given eg. `10`, `6` and `‹`,  10 will be decremented and the result will then be fed as an argument, for 6 times, resulting in `4`

**Comment by SE-Nitro** [comment]
Correction: An element that takes a list of args, an integer, and a lambda. It'll then output the nth value/s.

**Comment by Steffan153** [comment]
so this is like `ḞẎ` right?

**Comment by SE-Nitro** [comment]
@Steffan153 Oh, yes, but does that work?

**Comment by Steffan153** [comment]
Indeed it doesn't. Who messed that up?

**Comment by ysthakur** [comment]
Could you provide an example of how this would work?

**Comment by mathcat4** [comment]
what
