### ISSUE TITLE
Some kind of weird LazyList comparison bug

### ISSUE THREAD

**Issue by Steffan153** [Vyxal/Vyxal#1241]
Here's what you need to reproduce it: https://codegolf.stackexchange.com/a/249452/92689

> RuntimeError: cannot re-enter the tee iterator

Edit: here's much smaller code that can repro with (quite useless code though): [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLOu8Kj4oGwJ8KlOzvEsCIsIiIsIlsnaGVsbG8nLCAnd29ybGQnLCAnYmEnXSJd)

In that one, `~¥` works, but not `~λ¥;`.

**Comment by cgccuser** [comment]
Why are we still using `tee` btw? We no longer need to make copies the same way, right?

**Comment by Steffan153** [comment]
I don't think the error has to do with `itertools.tee` though. I mean, look in the code and stack trace.

**Comment by chunkybanana** [comment]
This is probably my fault.

**Comment by Lyxal** [comment]
seems to be fixed - something in the great bug fix must have resolved what was happening.
