### ISSUE TITLE
Strings are sometimes outputted without quotes in lists

### ISSUE THREAD

**Issue by Steffan153** [Vyxal/Vyxal#1242]
I've encountered this bug many times, but here's the most recent thing I did that did it: [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLOu+G5qjvEsCIsIiIsIlsnaGVsbG8nLCAnd29ybGQnLCAnYiddIl0=)

**Comment by chunkybanana** [comment]
I discovered this a while ago. What's weirder is that sometimes these strings aren't actually strings...
