### ISSUE TITLE
Ranges bug: `k≈` and `2ʁ` don't behave the same as `⟨0|1⟩`, and `ʀ∆F` and `ʀ∆f` behave alike

### ISSUE THREAD

**Issue by Davidebyzero** [Vyxal/Vyxal#1269]
`k≈⟨0|1⟩⁼` and `2ʁ⟨0|1⟩⁼` both return `1`, but `⟨0|1⟩` does not behave the same as `k≈` or `2ʁ` in at least one other way.

`⟨0|1⟩?(₍t∑)h` counts properly through the 0-indexed Fibonacci numbers, but `k≈?(₍t∑)h` and `2ʁ?(₍t∑)h` take a 2-iteration detour before going onward as they should. `2ʁ?(₍t∑)` for illustrative purposes:

```
0 => ⟨ 0 | 1 ⟩
1 => ⟨ 1 | 0 ⟩
2 => ⟨ 0 | 1 ⟩
3 => ⟨ 1 | 1 ⟩
4 => ⟨ 1 | 2 ⟩
5 => ⟨ 2 | 3 ⟩
6 => ⟨ 3 | 5 ⟩
7 => ⟨ 5 | 8 ⟩
8 => ⟨ 8 | 13 ⟩
9 => ⟨ 13 | 21 ⟩
```

[Try it Online!](https://vyxal.pythonanywhere.com/#WyJBIiwiIiwiMsqBPyjigo104oiRKSIsIiIsIjBcbjFcbjJcbjNcbjRcbjVcbjZcbjdcbjhcbjlcbjEwXG4xMVxuMTJcbjEzXG4xNFxuMTVcbjE2XG4xN1xuMThcbjE5XG4yMFxuMjFcbjIyXG4yM1xuMjRcbjI1XG4yNlxuMjdcbjI4XG4yOVxuMzAiXQ==)

This actually appears to be a bug with ranges. `ʀ∆F` returns the same thing as `ʀ∆f`, even though `∆F` and `∆f` alone work as they should:
```
∆F?ʀ∆FW
```
[Try it Online!](https://vyxal.pythonanywhere.com/#WyJBIiwiIiwi4oiGRj/KgOKIhkZXIiwiIiwiMFxuMVxuMlxuM1xuNFxuNVxuNlxuN1xuOFxuOVxuMTBcbjExXG4xMlxuMTNcbjE0XG4xNVxuMTZcbjE3XG4xOFxuMTlcbjIwXG4yMVxuMjJcbjIzXG4yNFxuMjUiXQ==)

**Comment by Steffan153** [comment]
These two issues are completely unrelated, btw. The reason `⟨0|1⟩` is not the same as k≈ or 2ʁ is because the former is a `list`, but the latter is a `LazyList`.

**Comment by Davidebyzero** [comment]
Is it not a bug that `k≈` isn't behaving the way I want? Because if so, that's really disappointing. `0 1W` is 2 more bytes than `k≈`.

Granted, I can find a workaround, for example `0 1?(:„+)`, but this makes `k≈` less useful for golf, doesn't it?

**Comment by Steffan153** [comment]
It is a bug, and I'm fixing it.
