### ISSUE TITLE
Permalinks not decoding on mobile

### ISSUE THREAD

**Issue by Lyxal** [Vyxal/Vyxal#127]
This probably has something to do with the recent placing of everything into external files.

Okay so say you are browsing code golf, and you see an epic link to the online interpreter. We'll call that link `https://lyxal.pythonanywhere.com/?flags=&code=%60this%20sentence%20is%20false&inputs=&header=&footer=` ([Try it online](https://lyxal.pythonanywhere.com/?flags=&code=%60this%20sentence%20is%20false&inputs=&header=&footer=))

Now, you're on your computer, and you open it. Everything is hunky dory. The link loads fine, all the relevant fields are filled, and everyone is happy.

Later, you go and visit the same link on your phone. The page loads, but the code box is empty. You figure that maybe the site is just taking a while to load it, so you wait for a moment. 10 seconds later, the permalink still hasn't decoded properly, and everything is still blank.

Confused, you try other links to the online interpreter on your phone. None of them work. You get your computer and leave a message in the Vyxal chatroom, only to find out that the links work on other people's computers. 

But then it's mentioned that the links don't work on their devices either. <s>And then you remember that someone recently placed all the site's JavaScript into an external file. You realise that in doing so, the internal workings of CodeMirror has somehow broken.</s> Nevermind. The external file isn't the problem

That's this issue.

## Relevant Error messages

```
main.js:285 Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at initCodeMirror (main.js:285)
    at onload (?flags=&code=`this sentence is false&inputs=&header=&footer=:196)
```

```js
box = $('#' + boxId).parent().children('div').children().not('[class]').children()[0];
```

Here is the site being simulated on a phone display: 

![](https://i.stack.imgur.com/hWkzS.png)

Yet it works on other phone displays:

![](https://i.stack.imgur.com/98u7i.png)

**Comment by ysthakur** [comment]
I wonder which idiot did something like that, definitely wasn't me. I can't see the source because I'm on mobile, but it looks like the CodeMirror text areas simply haven't loaded. Might need to use a callback for the focusin event listeners.

**Comment by ysthakur** [comment]
Also, can someone confirm that this used to work before?

**Comment by Lyxal** [comment]
```js
for (boxId of ['header', 'code', 'footer']) {
    box = $('#' + boxId).parent().children('div').children().not('[class]').children()[0];
    const capturedId = boxId;
    console.log(`${box}, ${boxId}`)
    box.addEventListener('focusin', event => {
        selectedBox = capturedId
    })
}
```

**Comment by Lyxal** [comment]
That's where it goes wrong. Deleting the above makes it work on mobile again

**Comment by ysthakur** [comment]
Can you try replacing the second line with box=globalThis["e_"+boxId].getTextatea()? (Idk the exact name of the method but you can try it put in the console to see)
