### ISSUE TITLE
Transliterate with multi-char strings doesn't work

### ISSUE THREAD

**Issue by Steffan153** [Vyxal/Vyxal#1326]
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCJgYWJjZGAgYGFiYCBgY2RgXCIg4biCIMS/IiwiIiwiIl0=) Should be `cdab`.

**Comment by chunkybanana** [comment]
This sort of pattern matching is quite difficult. It's not a bug, it's a feature. We might still be able to add this though...

**Comment by Lyxal** [comment]
Difficulty downgraded to easy, because it's a port of the v3 `String, String, String` method
