### ISSUE TITLE
Add "default values" for `n` and inputs

### ISSUE THREAD

**Issue by Steffan153** [Vyxal/Vyxal#1329]
Aka `⁰¹?n`. Currently, `⁰¹` error if it doesn'te xist, and the other two are just `0`. We could, for example, set `n` to be default `32`, etc, using common constants. One could maybe be for `ka` (alphabet).

**Comment by mathcat4** [comment]
Apparently, the most common constants are `ka`, `kA`, (`kH`), `kd` and `kP`
