### ISSUE TITLE
online interpreter's available tab shortcut words should be exposed as a list of suggestions

### ISSUE THREAD

**Issue by sporeball** [Vyxal/Vyxal#1331]
is this planned / even possible?

**Comment by Lyxal** [comment]
It's something we've kinda been half thinking about - now's our chance to discuss logistics of it

**Comment by cgccuser** [comment]
This would be very helpful. Codemirror does have stuff for [autocompletion and suggestions](https://codemirror.net/examples/autocompletion/), seems like it'd be doable

**Comment by Lyxal** [comment]
If there's ever a resurgence of interest and people available to implement this, it can be reopened
