### ISSUE TITLE
Add lambda to newline

### ISSUE THREAD

**Issue by Steffan153** [Vyxal/Vyxal#1342]
We can use `)`, so if no `(` is opened, then it does lam to newline

**Comment by chunkybanana** [comment]
Why would you want this though? It's just `λ...;` but with different delimiters, right?

**Comment by Steffan153** [comment]
`λcomplex code;[some element that takes function]` => `complex code)[some element that takes function]`

**Comment by chunkybanana** [comment]
Ah.

**Comment by chunkybanana** [comment]
We could create analogs of this with `];}`?

**Comment by Steffan153** [comment]
Wdym? `[...)` should behave the same as `[...])`, of course. But for `(...)` you'd have to do `(...))` if you wanted a lambda.
