### ISSUE TITLE
Perform base decoding when a small charset's present

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#1346]
(aka how to cheat at restricted source)

It would be cool if, when a program consists of 4 or less (subject to change) distinct characters each occuring at least thrice each, the program is decoded as unary/binary/ternary/etc using those chars. Maybe the first n characters could define the encoding?

For example, `xyxyxxxxyyyxyyyxxx` could be decoded as binary, with the `xy` representing that `x` represents 0 and `y` represents 1. This would become 17336, which would become `CḂ` when interpreted as code.

Thoughts?

**Comment by Steffan153** [comment]
This sounds cool, but we might want to add a flag to disable it, just in case.

**Comment by Lyxal** [comment]
Is this still a good idea?

**Comment by ysthakur** [comment]
It feels a bit cheaty. Isn't there the option of range coding now, anyway?
