### ISSUE TITLE
Rangified sublists is useless

### ISSUE THREAD

**Issue by Steffan153** [Vyxal/Vyxal#1374]
[Try it Online!](https://vyxal.pythonanywhere.com/#WyJSIiwiIiwiw55TIiwiIiwiMjUiXQ==)

**Comment by cgccuser** [comment]
It doesn't seem like it's being treated as a proper range? [This](https://vyxal.pythonanywhere.com/#WyJSIiwiIiwiMjXKgcOeUyIsIiIsIiJd) works properly

**Comment by Steffan153** [comment]
The problem is, it has a special case for when the input is a number, by concatenating the digits. It needs to check if rangify is on, and if so, not smash.

Or, just make it always rangify.
