### ISSUE TITLE
Round on some fractions rounds down

### ISSUE THREAD

**Issue by Steffan153** [Vyxal/Vyxal#1376]
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCI4Ni41IOG5mSIsIiIsIiJd)

**Comment by Lyxal** [comment]
This is called [Banker's rounding or round half to even](https://en.wikipedia.org/wiki/Rounding#Round_half_to_even), and it's the default rounding mode [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754) operations for results in binary floating-point formats

**Comment by Steffan153** [comment]
Bruh, it's annoying, but whatever. I've never seen a language that does this
