### ISSUE TITLE
Vylight doesn't highlight two-char strings

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#139]
When using the `‛` command for two-character strings, the command is highlighted as part of a string, but the characters in the string are not.

[Try it Online!](https://lyxal.pythonanywhere.com?flags=&code=%E2%80%9B9k&inputs=&header=&footer=)

**Comment by chunkybanana** [comment]
Fixed this a while ago, didn't notice the issue. Plz ping me in chat, I rarely check github.
