### ISSUE TITLE
Add element for matrix 2D convolution

### ISSUE THREAD

**Issue by Steffan153** [Vyxal/Vyxal#1401]

**Comment by Lyxal** [comment]
So what exactly does 2d convolution mean? Is it a monadic or dyadic thing? What are some examples of 2d convolution?

I don't know matrix terms very well, that's all.

**Comment by Steffan153** [comment]
im not really sure how u actually implement it but its this matlab thing

http://matlab.izmiran.ru/help/techdoc/ref/conv2.html
https://www.mathworks.com/help/matlab/ref/conv2.html

luis uses it constantly in his matl answers so it must be useful

**Comment by Lyxal** [comment]
Got it. I'll look into it and see what I can come up with
