### ISSUE TITLE
`K` flag not outputting correctly

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#142]
The `K` flag is supposed to input strings as lists of ordinal values, and output numbers as characters. It is inputting correctly, but numbers still get outputted as numbers.

Example: [Try it Online!](https://lyxal.pythonanywhere.com?flags=K&code=&inputs=Hello%2C%20World!&header=&footer=)

**Comment by ysthakur** [comment]
Perhaps [this line](https://github.com/Vyxal/Vyxal/blob/master/vyxal/interpreter.py#L2978) could use `isinstance(Number, item)`?

**Comment by Lyxal** [comment]
It would have to be `VY_type(item) == Number`, because Number is just a string and only VY_type returns Number as a type

**Comment by Lyxal** [comment]
It seems to be working as intended.
