### ISSUE TITLE
Make the REPL a bit nicer to use

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#1445]
Currently, the repl is mostly used for debug purposes - compiled code is printed, and each piece of code is executed with its own context and stack. It would be nice to have a opt-in/opt-out way to toggle this debugging functionality.

Additionally (idk how hard or easy this is) up-arrow and down-arrow would be nice to select previous snippets, and it'd be cool if <kbd>^C</kbd>ing while the repl was executing something only exited that execution, not the entire repl.

**Comment by GingerIndustries** [comment]
Perhaps a Vyxal REPL deserves its own project? I'd be happy to make it, once I find time :p

**Comment by GingerIndustries** [comment]
In progress here: https://github.com/Vyxal/Crosshatch/

**Comment by ysthakur** [comment]
Should there be a `.vyxal_history` file or should it only remember the current session's history when you hit the up arrow?
