### ISSUE TITLE
Make diagonals in a more sensible order

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#1447]
Currently, the diagonals and antidiagonals builtins output the main (antidiagonal), all the ones down from there, and then the rest. This is annoying and often requires an `IRƒJ` or similar to fix. It would be much more intuitive to have it start at the shortest top diagonal and work its way down, i.e. for:

```
1 1 0 1
0 1 0 1
1 0 1 0
0 0 0 1
```

Diagonals would be `[[1], [0, 1], [1, 0, 0], [1, 1, 1, 1], [0, 0, 0], [1, 0], [0]]` and antidiagonals woudl be `[[1], [1, 0], [0, 1, 1], [1, 0, 0, 0], [1, 1, 0], [0, 0], [1]]

**Comment by tobyck** [comment]
Could this be a backwards compatibility issue or do you think it's fine?

**Comment by ysthakur** [comment]
@tobyck Lyxal added new digraphs and kept the old ones for backwards compatibility, so I guess it'll be fine.
