### ISSUE TITLE
Make monadic ranges work with negative numbers

### ISSUE THREAD

**Issue by tobyck** [Vyxal/Vyxal#1477]
At the moment [`5Nɾ`](https://vyxal.pythonanywhere.com/#WyIiLCIiLCI1Tsm+IiwiIiwiIl0=) (and all the other monadic ranges) yields an empty list instead of something like `[-1, -2, -3 ...]`.

**Comment by Steffan153** [comment]
This might be intended behavior. It's sometimes useful.

**Comment by tobyck** [comment]
Ah, ok
