### ISSUE TITLE
BUG: Parsing strings containing the two-byte string delimiter errors during parsing

### ISSUE THREAD

**Issue by hyper-neutrino** [Vyxal/Vyxal#148]
Currently if the string being parsed contains a two-byte string delimiter, since Group Two Byte Strings (GTBS) inserts a list into the source list, it does not get appropriately added into the list during Group Strings (GS). Instead, GTBS should either skip the delimited if during a regular string, or GS needs to account for GTBS's output formatting.

**Comment by Lyxal** [comment]
Wow I forgot to close this with the commit
