### ISSUE TITLE
Apply at indices is broken

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#1519]
[And it's lyxal's fault](https://github.com/Vyxal/Vyxal/commit/ec65394d0a010f9070ca9254a0c1fbb0b1e33eba)

**Comment by Lyxal** [comment]
Test program? Expected output? Description of how it's broken?

I can't fix something if I don't have details on what you mean.

**Comment by ysthakur** [comment]
@Lyxal Looks like `assign_iterable` returns a generator instead of a LazyList. Should be easy to fix.

**Comment by Lyxal** [comment]
>  So, it's using the indices in the string when it should be using the indices in the replaced part. For example, applying "reverse" to the elements of "abcde" at indices 1, 3 should produce adcbe but instead it produces abcbe, because it's using 1 and 3 to index into "db" instead of 0 and 1. 

> https://vyxal.pythonanywhere.com/#WyIiLCIiLCJgYWJjZGVg4oG94bmY4p+oMXwz4p+pwqIiLCIiLCIiXQ==

[From chat](https://chat.stackexchange.com/transcript/106764?m=62709341#62709341)

**Comment by Lyxal** [comment]
Forgot to paste that here when it was mentioned :p

**Comment by Lyxal** [comment]
> @Lyxal Looks like `assign_iterable` returns a generator instead of a LazyList. Should be easy to fix.

but that's probably a bug too.

**Comment by Lyxal** [comment]
double bug

**Comment by ysthakur** [comment]
Serendipity

**Comment by ysthakur** [comment]
Ah, the assign_iterable thing has been fixed now

**Comment by Lyxal** [comment]
only single bug?

dang

**Comment by Steffan153** [comment]
Chat is a thing, you don't have to post a new github message for everything

**Comment by Lyxal** [comment]
I know.
