### ISSUE TITLE
FR: API

### ISSUE THREAD

**Issue by hyper-neutrino** [Vyxal/Vyxal#153]
This is a feature request for an API for the online interpreter. Ideally, a client would be able to send a POST request with JSON data containing the flags, the code, and the inputs, and it would return the STDOUT and STDERR. To prevent abuse (although one can already run a slow program and spam requests through the front-end), it could require API keys to be used and given only to trusted users.

This would help the Vyxal executor bot stay up-to-date and run code as it would be run on the production page.

**Comment by ysthakur** [comment]
Since [this is apparently a thing](https://chat.stackexchange.com/transcript/message/58599986#58599986) already, I'm closing this.
