### ISSUE TITLE
Implicit match from the start.

### ISSUE THREAD

**Issue by Fmbalbuena** [Vyxal/Vyxal#1537]
`{|,}1` would perform the same task as `|,}1` (Output 1 if input is 0, else output 1 infinitely if input is 1).

Must work for lists and conditionals.

**Comment by Aurathic** [comment]
This might be a silly approach, but couldn't you just check the whole string for unpaired close brackets and prepend as many open brackets as necessary to match them?

**Comment by ysthakur** [comment]
Any takers? Would be useful if it's not too hard to implement

**Comment by Lyxal** [comment]
This would only be able to be implemented for `]` and `}`, as `)` has special meaning.

**Comment by Fmbalbuena** [comment]
@Lyxal Does `;` count?

**Comment by Lyxal** [comment]
There's no way to unambiguously tell what the matching opening bracket for a `;` would be because it's used for multiple things

**Comment by Fmbalbuena** [comment]
@Lyxal Then use flags for that.

**Comment by Seggan** [comment]
mm yes, flags, the fix for everything

**Comment by Lyxal** [comment]
I don't think this seems to be a feasible thing to implement going forward. Definitely not in vyxal 3 where only `}` closes things, and vyxal 2 already has different meanings for closing brackets not associated with strutures.
