### ISSUE TITLE
Extend Valid Digit Range Of R (String Base Conversion From Decimal)

### ISSUE THREAD

**Issue by Aurathic** [Vyxal/Vyxal#1568]
Currently, `R` encodes base 10 numbers in a string using the symbols `0-9A-Z`, which limits it to conversions up to base 36. I suggest extending the symbol set to `0-9A-Za-z` allowing conversions up to base 62.

**Comment by ysthakur** [comment]
That's a good point, but sometimes you might want case-insensitivity. Perhaps we could have a digraph that uses `0-9A-Z`, keeping `R`'s old behavior, and modify `R` like you said? (or the other way around, keep `R` the same and add a digraph to encode up to base 62)

**Comment by Aurathic** [comment]
It's true that sometimes case insensitivity is a plus, but adding extra symbols to the set doesn't affect the encodings for any numbers less than 37; unless the program crashing is a desired effect of providing a parameter over 36, this change shouldn't harm any programs which already use the current implementation. (Also, hello from a former Blazer :) )

**Comment by ysthakur** [comment]
That makes sense (also, small world!)
