### ISSUE TITLE
Bug: Dictionary Compression Isn't Optimal

### ISSUE THREAD

**Issue by Aurathic** [Vyxal/Vyxal#1570]
**Describe the bug**
Dictionary compression does not always output the optimal compressed string. For example, when trying to compress "Anchorage", `øD` produces `ε₈age`, ending with the word `age`, which obviously can be compressed as `⟇§` instead, saving a byte.

**Example program**

```
øD,
```

[Try it](https://vyxal.pythonanywhere.com/#WyIiLCIiLCJgQW5jaG9yYWdlYMO4RCxcbmDOteKCiOKfh8KnYCwiLCIiLCIiXQ==)

**Expected Output**

```
["Anchorage"] -> ε₈⟇§
```

**Comment by mathcat4** [comment]
I don‘t think it works like that - ˋ ε₈⟇§ˋ stands for something else. I don‘t think limiting compressions to just contain non-words would make it any shorter.

**Comment by Aurathic** [comment]
When I input `ε₈⟇§`, it decompresses to `Anchorage` [link](https://vyxal.pythonanywhere.com/#WyIiLCIiLCJgzrXigojin4fCp2AsIiwiIiwiIl0=), so unless the decompression is working improperly then I'm not sure what else ˋ ε₈⟇§ˋ stands for.

**Comment by mathcat4** [comment]
Oh nvm then.

**Comment by Aurathic** [comment]
Trying it on some other string:
- `AnchorAge` works
- `Anchoraage` works
- `Anchorden` works
- `Informationage` works
- `anchorage` *doesn't* work
- `otherage` does compress `age`, but it results in a 5-byte string `oλλṠ⟨` instead of the more optimal 4-byte `λṁ⟇§`
