### ISSUE TITLE
Vyxal Program as Optional Argument

### ISSUE THREAD

**Issue by Aurathic** [Vyxal/Vyxal#1572]
In Python, one can use the `-c` flag to add the executable program as an argument to the program call, e.g. `python -c 'print("Hey")'`. It could be useful if Vyxal had the same feature for rapid prototyping within the command prompt.

**Comment by ysthakur** [comment]
You can actually use the `e` flag and pass a program, I think

**Comment by Lyxal** [comment]
As user said, this exists as the e flag
