### ISSUE TITLE
Much feature requests

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#160]
### Constants
- [x] `kT` - BF command set
- [x] `kṗ` - List  of all bracket pairs - `[(),[],{},<>]`
- [x] `kṖ` - All brackets nested - `([{<>}])`
- [x] `kg` - Phi
- [x] `kS` - Amogus (`ඞ`)
- [x] `k₂` - 2^20
- [x] `k₃` - 2^30
- [x] `k∪` - lowercase vowels with `y`
- [x] `k⊍` - uppercase vowels with `y`
- [x] `k∩` - both cases of vowels with `y`
- [x] `Þo` -Infinite list of ordinals
- [x] `Þc` - Infinite list of cardinals
- [x] `Þp` - Infinite list of primes
### Flags
- [x] #407
- [x] #408
- [x] `t` - Lists are truthy if any item is truthy, else falsy
- [x] #456
- [x] #455
- [x] `2` - Default lambda arity = 2
- [x] `3` - Default lambda arity = 3
### String stuff
- [x] `øb` = Enclose in `()`
- [x] `øB` = Enclose in `[]`
- [x] `øḃ` = Enclose in `{}`
- [x] `øḂ` = enclose in `<>`
- [x] `øβ` - Are brackets (`(),{},[],<>`) balanced?
- [x] `ø↳` and `ø↲` = custom left / right padding
- [x] `øĿ` - Ring translate
- [x] `øv` -  Is_vowel - handles like `C` for multichar strings
- [x] `øċ` - Is_uppercase - handles like `C` for multichar strings, 1 if char is an uppercase ASCII letter, else 0
- [x] `øM` = Palindromise (don't duplicate middle) with ascii-art swap mappings
### Number stuff
- [x] `∆i` - nth-digit-of-pi
- [x] `∆ė` - nth-digit-of-e
- [x] `∆I` - First n digits of pi
- [x] `∆Ė` - First n digits of e
- [x] `∆f` - nth-fibonacci-number
- [x] `∆ε` - Evaluate polynomial equation with coefficents and variable
- [x] `ÞB` -  Array of random bits to length n 
- [x] `∆Z` - zfill - prepend 0s to a until it's length b
### Other stuff
- [x] #399
- [x] `Þu` - All_unique
- [x] `ÞẊ` - Cartesian power
- [x] `Þx` - `Þ×` but with replacements
- [x] `Þf` - Flattento  a certain depth
- [x] `øṖ` - All partitions of a string
- [x] #401
- [x] `ÞC` - Cut into chunks of specified length (stolen from osabie)
- [x]  `Þ<` - All of a list that are less than a certain number (Assume increasing, stop as soon as you find a value ≥ that number)
- [x] `Þǔ` - Untruth - A boolean array with 1s at the elements in a, and 0s everywhere else(Stolen from Jelly)
- [x] `Þi` - Multidimensional indexing - take an array of indices and index into a multidimensional array
- [x] `Þḟ` - Multidimensional searching - find the first (multidimensional) occurence of a value
- [x] #402
- [x] #403
- [x] #404
- [x] #405
- [x] `Þm` - Given list of dimensions, create a matrix with those dimensions, filled with zeroes
- [x] `ÞZ`  - Fill by coordinates - Given function + list, call with each (potentially multidimensional) coordinate of list, as list of integers, and insert result into corresponding location
### Modifications
- [x] Random choice from a number picks a random number between 0 and n, modifiable with `mM` flags
- [x] `İ` vectorises fully on the right side - not erroring when given a nested list, instead going through every item
- [x] `⌊` needs to play nice with strings not containing digits.
- [x] `øȯ` should be able to take a list of strings to remove
- [x] Modify `Ẏ` so if given an index to slice to greater than the length, repeat items until it's at the required length.

**Comment by Lyxal** [comment]
consonants already exist

**Comment by Lyxal** [comment]
2^20, 2^30 have been added

**Comment by ysthakur** [comment]
- [ ] √2
- [ ] √3
- [ ] √5
- [ ] Þ0, Þ1, etc = list of length a filled with appropriate value - also something for "list of length a filled with b"
- [ ]     Phi
- [ ] 2^20
- [ ] 2^30
- [ ]     Triple / mod 3 would be nice (overload G/g?)
- [ ]     nth-digit-of-pi
- [ ]   nth-digit-of-e
- [ ]  nth-triangle-number
- [ ]  nth-fibbonaci-number functions
- [ ]     Vowels with y
- [ ]     Consonants
- [ ]     (Non-ascii)(ascii) processed as new SCCs in strings - +15k words

**Comment by Lyxal** [comment]
I've unticked everything so we can retick it as we implement it

**Comment by ysthakur** [comment]
> Amogus (ඞ) because why not

Because it's sus.

More seriously, we do *not* need that as a character in the codepage taking up valuable space. Maybe it'd be a "fun" digraph to have, but...why do you even want it?

**Comment by pxeger** [comment]
@ysthakur I think it was meant to be a constant. So `kṠ` would return the string `ඞ` or something

**Comment by ysthakur** [comment]
I see, I thought that `ඞ` would return `"Amogus"`.

**Comment by Lyxal** [comment]
You know 2^20 and 2^30 are already in v2.4?

**Comment by Lyxal** [comment]
*2.5

**Comment by pxeger** [comment]
@Lyxal

> https://github.com/Vyxal/Vyxal/issues/160#issuecomment-887375407

**Comment by ysthakur** [comment]
@razetime Ah, I guess that'd work. Not the highest priority, though 😄.

**Comment by Lyxal** [comment]
Mold to length? Isn't that just `•` with extra steps?

**Comment by Lyxal** [comment]
Also, I need more specifications on what you mean by ring translate.

**Comment by razetime** [comment]
@Lyxal Map matching elements to the subsequent element in the translation ring. The ring wraps around.

Useful in [ascii-art] and [string].

so: `['a',b'], "bab" → "aba"`

**Comment by Lyxal** [comment]
A note on `øĿ` - it's now a overload for `*`

**Comment by chunkybanana** [comment]
Finally! It's over...
