### ISSUE TITLE
Bug: no cookie in v3 :(

### ISSUE THREAD

**Issue by GingerIndustries** [Vyxal/Vyxal#1607]
**Describe the bug**
no cookie in v3 ;-;

how to baek cooki? I tri for thirtee minut but no baek

**Example program**

```
🍪
```

**Expected Output**

```
cookie
cookie
cookie
cookie
cookie
cookie
cookie
cookie
cookie
cookie
cookie
cookie
cookie
cookie
cookie
cookie
cookie
cookie
cookie
cookie
cookie
cookie
```

**Other things**

🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪🍪

**Comment by ysthakur** [comment]
See [`_`'s implementation](https://github.com/Vyxal/Vyxal/blob/version-3/shared/src/main/scala/Elements.scala#L290) for an example of how to implement cookie

**Comment by Lyxal** [comment]
> Actually, this requires UTF-8 support first, so maybe not the easiest thing to implement.

What do you mean utf-8 support? Files aren't read as UTF-8 already?
