### ISSUE TITLE
Bug: `İ` elements 'collect while unique' overload doesn't work correctly

### ISSUE THREAD

**Issue by AndrovT** [Vyxal/Vyxal#1633]
Collect while unique overload of `İ` returns an empty list if it doesn't reach a fixed point. It works as expected if it does reach a fixed point.

**Examples**

```
0λ›3%;İ
```

[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIwzrvigLozJTvEsCIsIiIsIiJd)

Expected output: `⟨ 1 | 2 | 0 ⟩`
Actual output: `⟨  ⟩`

```
0λ›3∵;İ
```

[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIwzrvigLoz4oi1O8SwIiwiIiwiIl0=)

Expected output: `⟨ 1 | 2 | 3 ⟩`
Actual output: `⟨ 1 | 2 | 3 ⟩`

**Comment by Lyxal** [comment]
> Expected output: `⟨ 1 | 2 | 3 ⟩`
> Actual output: `⟨ 1 | 2 | 3 ⟩`

Aren't those the same?
