### ISSUE TITLE
Enhancement: Add More Graph Digraphs

### ISSUE THREAD

**Issue by Aurathic** [Vyxal/Vyxal#1673]
There are many Code Golf problems which can be easily reduced to graph problems, but Vyxal doesn't have the utilities for this, e.g.
- Is this graph connected? (alternatively, how many disjoint subgraphs are in this graph, or what are the disjoint subgraphs in this graph?)
- What are the cycles in this graph?
- Converting between adjacency lists and matrices
And other things I'm forgetting.

**Comment by Steffan153** [comment]
If we add builtins for everything, golfing gets boring. I'm not sure if these are necessary.
