### ISSUE TITLE
Enhancement: Rotation (`Ǔ` / `ǔ`) should be modular

### ISSUE THREAD

**Issue by nayakrujul** [Vyxal/Vyxal#1678]
See [this program](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLHlCIsIiIsIjVcbkFCQ0QiXQ==). It's trying to rotate `ABCD` right 5 times, but since `5 > len('ABCD')`, it just doesn't do anything. Instead, rotation should be modular, and rotating `ABCD` right 5 times should result in `DABC`.

**Comment by ysthakur** [comment]
Shush, bot. Thanks for making the issue, nayakrujul. It looks like for strings, we're using [Python slices](https://github.com/Vyxal/Vyxal/blob/main/vyxal/elements.py#L5496), which is probably what's causing the issue. Throwing a couple modulos in there should fix it.
