### ISSUE TITLE
No equivalent to APL's ∘. (outer product)

### ISSUE THREAD

**Issue by JoaoFelipe3** [Vyxal/Vyxal#1696]
APL has an operator (yes, in APL we have functions and operators) which is called outer product, and it allows to take two arrays and matrixify them by executing a function on each pair of elements. Example:
```
∘.+⍨⍳3
```
results in:
```
2 3 4
3 4 5
4 5 6
```

I would like to have the same thing in Vyxal, but with lists instead of arrays. Something like `Þȯ` would work. Example:

```
3ɾ:⁽+Þȯ
```
would result in:
```
⟨ ⟨ 2 | 3 | 4 ⟩ | ⟨ 3 | 4 | 5 ⟩ | ⟨ 4 | 5 | 6 ⟩ ⟩
```

Please add this. Also, description:
```
Does APL's outer product.
fun, lst, lst -> b∘.ac
```

**Comment by Steffan153** [comment]
[`vv`](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIzyb46dnYrIiwiIiwiIl0=) (double vectorize) does this. (you can often omit the second `v` if the element vectorizes)

**Comment by JoaoFelipe3** [comment]
Welp.
