### ISSUE TITLE
Bug: The `~` flag doesn't work with other flags

### ISSUE THREAD

**Issue by nayakrujul** [Vyxal/Vyxal#1703]
The `A` flag does, so why doesn't the `~` flag?

See [this program](https://vyxal.pythonanywhere.com/#WyJ+cyIsIiIsIiIsIiIsIlsxLCAyLCAzXSA9PiA2XG5bMywgNCwgNV0gPT4gMTIiXQ==). Its equivalent [`A` flag version](https://vyxal.pythonanywhere.com/#WyJBcyIsIiIsIiIsIiIsIlsxLCAyLCAzXSAjPT4gNlxuWzMsIDQsIDVdICM9PiAxMiJd) works.

**Comment by nayakrujul** [comment]
I don't think it needs urgent attention, so I've added the medium priority tag. Feel free to upgrade/downgrade if you want.

**Comment by nayakrujul** [comment]
@Lyxal `ctx.online_output[1]` is a string, right?

Because if it is, could getting the length and then slicing it work? Something like this:

```python
for inp in inputs:
    # Handle the input
    if online_mode:
        slice_start = len(ctx.online_output[1])
        # Call execute_vyxal like the A flag does
        printed_text = ctx.online_output[1][slice_start:] # That's what was printed when we called execute_vyxal
        # Assert that printed_text is what we expected
```

Note: this is just a fix for the online mode, not sure what we would need for the offline interpreter.

**Comment by Lyxal** [comment]
That could probably be made to work offline

**Comment by nayakrujul** [comment]
But would it work?

**Comment by Lyxal** [comment]
In theory I think

**Comment by nayakrujul** [comment]
If `ctx.online_output[1]` is a string and `execute_vyxal` adds to the string, then it would work, right?

**Comment by nayakrujul** [comment]
So should I make a PR for it?

**Comment by Lyxal** [comment]
Go for it.

**Comment by nayakrujul** [comment]
We really overestimated the amount of work that would have to go into that didn't we
