### ISSUE TITLE
Vyncode: Bytecount doesn't update after using ␠ or ␤ 

### ISSUE THREAD

**Issue by nayakrujul** [Vyxal/Vyxal#1731]
I can't give you a link because it won't let me, but if you use the `=` flag with either `␠` or `␤` in the code box, it won't update the bytecount to a Vyncode one.

(Observation made by Aiden Chow [here](https://chat.stackexchange.com/transcript/message/63489873#63489873))

**Comment by Lyxal** [comment]
Different issue
