### ISSUE TITLE
Avoid double-wrapping in `VList.from`

### ISSUE THREAD

**Issue by ysthakur** [Vyxal/Vyxal#1743]
There are some cases in which `VList.from` might be passed a `VList`, so at runtime, it should check if its argument is a `VList` and, if so, return that list back instead of wrapping it in yet another `VList`.

**Comment by shaiksamad** [comment]
I think I can solve the issue, I am new to open source contribution, could you help me where is VList used.

**Comment by nayakrujul** [comment]
@shaiksamad thanks for helping out! You should now be able to make a pull request to get your changes onto the main repository. If you write `closes #1473` in that pull request, this issue will automatically close once that pull request is merged.

**Comment by nayakrujul** [comment]
@shaiksamad thanks! I've made the [pull request](https://github.com/Vyxal/Vyxal/pull/1747) for you. When that is merged, this issue will be closed.

**Comment by nayakrujul** [comment]
Didn't get closed? Anyway, closed by #1747
