### ISSUE TITLE
Bug: New wait instruction doesn’t seem to work.

### ISSUE THREAD

**Issue by PlaceReporter99** [Vyxal/Vyxal#1801]
**Describe the bug**
`¨w` doesn’t seem to work in online interpreter.

**Example program**

```
3¨w
```

[Try it](https://vyxal.pythonanywhere.com/?v=2#WyIiLCIiLCIzwqh3IiwiIiwiIl0=)

**Expected Output**

```
(takes 3 seconds to run and doesn’t output anything)
```

**Other things**

- I made the PR ( #1799 ) for this so I’m sorry if I did something wrong.

**Comment by nayakrujul** [comment]
For me it outputs 3:

<img width="1672" alt="Screenshot 2023-07-01 at 19 39 10" src="https://github.com/Vyxal/Vyxal/assets/55329600/81be9a8d-6428-42b1-a96e-799a54e1f97c">

**Comment by PlaceReporter99** [comment]
Now I get an error when running the same code:
```
Traceback (most recent call last):
  File "/home/Vyxal/mysite/vyxal/main.py", line 330, in execute_vyxal
    exec(code, locals() | globals())
  File "<string>", line 3, in <module>
TypeError: isinstance() arg 2 must be a type or tuple of types
```

**Comment by ysthakur** [comment]
#1803 should take care of this. Also, the online interpreter doesn't have the element yet because it hasn't been pushed to the production branch yet. I'm closing for now since it probably works fine.
