### ISSUE TITLE
Character literals shouldn't get decompressed

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#182]
When using `\` to make a character literal, if it is a non-ascii character, the interpreter attempts to decompress it, which returns an empty string since there is no second character to create a SCC. Obviously, you can use the `D` flag to combat this, but since a character literal can *never* be an SCC, it would make more sense to just not try to decompress it.

Example: [Try it Online!](https://lyxal.pythonanywhere.com?flags=&code=%5C%CE%BBq&inputs=&header=&footer=)

**Comment by chunkybanana** [comment]
This is a bug, it _used_ to work.
