### ISSUE TITLE
Bug: `ø%` isn't working...

### ISSUE THREAD

**Issue by PlaceReporter99** [Vyxal/Vyxal#1837]
**Describe the bug**
When I use the `ø%` element, it doesn't do anything.

**Example program**

```
`banana`ø%
```

[Try it](https://vyxal.pythonanywhere.com/?v=2#WyIiLCIiLCJgYmFuYW5hYMO4JSIsIiIsIiJd)

**Expected Output**

```
b493d48364afe44d11c0165cf470a4164d1e2609911ef998be868d46ade3de4e
```

**Other things**

- Version 2.21.6
- Seems to pass tests for some reason.

**Comment by Lyxal** [comment]
This was an issue with the website. It just needed manual reloading. Not a bug.

**Comment by PlaceReporter99** [comment]
phew
