### ISSUE TITLE
Two-char strings do be breaking parsing again

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#195]
Put `‛` inside a compressed string. Or a compressed number. Or a normal string. What happens? Nothing. Which is the opposite of what should happen. 'Cause it be bork.

Example: [Try it Online!](https://lyxal.pythonanywhere.com?flags=&code=%C2%BB%E2%80%9Bab%C2%BB&inputs=&header=&footer=)

**Comment by Lyxal** [comment]
Somebody isn't using the latest version smh
