### ISSUE TITLE
Bug: 100 lambdas causes an IntendationError

### ISSUE THREAD

**Issue by bbrk24** [Vyxal/Vyxal#1962]
**Describe the bug**
This will never happen in real code but it's funny

**Example program**

```
λλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλλ
```

[Try it](https://vyxal.pythonanywhere.com/?v=2#WyIiLCIiLCLOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOu867zrvOuyIsIiIsIiJd)

**Expected Output**

`0`, I think? That's what 99 of them does anyways

**Other things**

I don't know enough about Vyxal to answer any of the questions it's asking here (flags, forced evaluation, etc). I was just messing around.

**Comment by bbrk24** [comment]
WHAT

**Comment by GingerIndustries** [comment]
you cannot escape

**Comment by mathcat4** [comment]
I don't think there's an easy fix to this :p

**Comment by Lyxal** [comment]
There's always going to be some form of this issue, as it's a skill issue on python's end. The only fix would be switching away from transpilation, which is basically version 3.
