### ISSUE TITLE
String to number

### ISSUE THREAD

**Issue by GenericProgrammer1234** [Vyxal/Vyxal#1999]
Make a way to convert strings to numbers.

**Comment by AMiller42** [comment]
What should the behavior be for strings that contain non-numeric characters? i.e. return the original string, ignore all non-numeric characters, return 69, etc.

**Comment by lyxal** [comment]
v2 behaviour: strip non-numeric.

I'm actually working on this rn, even before you commented :p

**Comment by lyxal** [comment]
done
