### ISSUE TITLE
Missing Operations

### ISSUE THREAD

**Issue by pacmanboss256** [Vyxal/Vyxal#2000]
- <s>Set Intersection</s>
- <s>Symmetric set difference</s>
- multiset variants of the above 
- <s>GCD</s>
- <s>palindromise</s>
- <s>flatten by depth</s>
- <s>convert to number</s>
- <s>prime exponents</s>
- <s>nth prime</s>

**Comment by pacmanboss256** [comment]
-Item split (÷ in vyxal 2 list overload)

**Comment by lyxal** [comment]
> -Item split (÷ in vyxal 2 list overload)

This already exists. It's called dump

<code>\\</code>

**Comment by lyxal** [comment]
Done
