### ISSUE TITLE
Empty comments break the lexer

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#2001]
If the comment diagraph (`##`) is immediately followed by a newline or EOF, the lexer will error, and the program fails to run.

### Examples:
```
"oof"##
```
[Try it Online!](https://vyxal.github.io/latest.html#WyIiLCIiLCJcIm9vZlwiIyMiLCIiLCIiLCIzLjEuMCJd)
```
"oof but taller"##

```
[Try it Online!](https://vyxal.github.io/latest.html#WyIiLCIiLCJcIm9vZiBidXQgdGFsbGVyXCIjI1xuIiwiIiwiIiwiMy4xLjAiXQ==)
```
"yay"##no oof
```
[Try it Online!](https://vyxal.github.io/latest.html#WyIiLCIiLCJcInlheVwiIyNubyBvb2YiLCIiLCIiLCIzLjEuMCJd)

**Comment by lyxal** [comment]
Fixed.
