### ISSUE TITLE
Add regex built-ins

### ISSUE THREAD

**Issue by mathcat4** [Vyxal/Vyxal#2006]
eg. first match, all matches, return groups, ...

**Comment by lyxal** [comment]
Regex features (stolen from python's `re` library):

- <s>Search => return first index of `pattern` match</s>
- <s>Match => return the portion of the `string` that `pattern` matches</s>
- <s>Matches at all => return a boolean whether a match is present</s>
- <s>Matches Fully => return whether the entire string matches the pattern</s>
- <s>Split => Split a string on a `pattern`</s>
- <s>Find All => find all non-overlapping matches of `pattern` in string</s>
- <s>Find All overlapping => Find all but more painful to implement</s>
- <s>Substitute => Replace instances of pattern with string/function taking match as input</s>
- <s>Escape => Take a string and escape it</s>
- <s>Groups => Return a list of all groups of a match</s>
- <s>Span => Return the start and end position of a match</s>

Strikethrough represents implemented.
