### ISSUE TITLE
Fuzzed Issues

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#2017]
Issues found by the fuzzer.

- [x] Some modifiers (`ᵃᴴ`) error on elements implemented with `addDirect`
- [x] Vectorise (`ᵛ`) errors on nilads
- [x] Rotate (`ṙṘ`) errors on empty strings
- [x] Indexed inputs (`⁰¹`) error if not enough inputs are given
- [x] String Cast to Int (`⌊`) errors on non-numeric strings
- [x] Overlapping Slices (`o`) errors on negative numbers

**Comment by AMiller42** [comment]
Side note: If I understand correctly, I think a lot of the `addDirect` elements could be `addFull` instead, not sure if that should be changed.

**Comment by ysthakur** [comment]
> Side note: If I understand correctly, I think a lot of the `addDirect` elements could be `addFull` instead, not sure if that should be changed.

Yes addFull would be preferabe to addDirect, mpre information

**Comment by AMiller42** [comment]
I was incorrect about the nature of the first mentioned issue. The `ᴴ` modifier was erroring due to typecasting and arity issues, and the `ᵃ` modifier appears to be erroring because the `ȧ` element doesn't work on strings. It just happens that all of the elements I used to test were `addDirect` elements, and at the time I didn't fully understand what that meant.
