### ISSUE TITLE
vyxalVersion not updated for 3.4.0

### ISSUE THREAD

**Issue by TomaSajt** [Vyxal/Vyxal#2041]
https://github.com/Vyxal/Vyxal/blob/cd7fb9cffdb302ae18182b3de9851d4ac03b9c41/build.sc#L16
The above line above hasn't been updated to the new version, but the line below has
https://github.com/Vyxal/Vyxal/blob/cd7fb9cffdb302ae18182b3de9851d4ac03b9c41/shared/src/vyxal/Interpreter.scala#L11

Discovered this when looking at the releases and seeing the wrong version in the .jar filename

**Comment by lyxal** [comment]
Well, looks like it'll need to be re-released

**Comment by lyxal** [comment]
Fixed
