### ISSUE TITLE
Deploy workflow is failing

### ISSUE THREAD

**Issue by ysthakur** [Vyxal/Vyxal#2105]
The deploy workflow is [failing](https://github.com/Vyxal/Vyxal/actions/runs/9226998122/job/25387998078) with an error saying that `upickle.default.write` can't be found.

I suspect it's because of https://github.com/Vyxal/Vyxal/pull/2101, where @scala-steward updated the Scala Toolkit version (@scala-steward, don't worry, you're a good bot and we still love you. You could'n't've foreseen this). Both Mill and Scala Toolkit depend on upickle, and maybe the minor update to Scala Toolkit made it so that it now has a different version of upickle, causing weirdness.

**Comment by lyxal** [comment]
gotta be like the second or third time a Scala Steward PR has broken CI

**Comment by ysthakur** [comment]
Still a better track record than us two
