### ISSUE TITLE
Make Vyxal a package so it can be installed with pip

### ISSUE THREAD

**Issue by ysthakur** [Vyxal/Vyxal#246]
Making Vyxal a proper package would greatly ease installation. [Here's](https://packaging.python.org/tutorials/packaging-projects/) a tutorial on how to package projects.

**Comment by AMiller42** [comment]
I see you self-assigned this, but you also added the "help wanted" label. Are you planning on doing it yourself, or should someone else go ahead with this?

**Comment by ysthakur** [comment]
I'm working on it myself, but if anyone already knows how to do it, any help would be appreciated, since I don't know how to do it.

**Comment by PyGamer0** [comment]
> I'm working on it myself, but if anyone already knows how to do it, any help would be appreciated, since I don't know how to do it.

Just copy jelly
