### ISSUE TITLE
Digraphs to implement

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#269]
- [x] `∆c`
- [x] `∆C`
- [x] `∆q`
- [x] `∆Q`
- [x] `∆s`
- [x] `∆S`
- [x] `∆t`
- [x] `∆T`
- [x] `∆P`
- [x] `∆ƈ`
- [x] `∆±`
- [x] `∆K`
- [x] `∆²`
- [x] `∆e`
- [x] `∆E`
- [x] `∆L`
- [x] `∆l`
- [x] `∆τ`
- [x] `∆d`
- [x] `∆D`
- [x] `∆R`
- [x] `∆Ṗ`
- [x] `∆ṗ`
- [x] `∆p`
- [x] `∆ṙ`
- [x] `∆Ṙ`
- [x] `∆W`
- [x] `∆Ŀ`
- [x] `øṖ`
- [x] `Þo`
- [x] `Þc`
- [x] `Þp`
- [x] `Þu`
- [x] `ÞẊ`
- [x] `Þf`
- [x] `ÞB`
- [x] `Þ<`
- [x] `Þǔ`
- [x] `Þi`
- [x] `Þḟ`
- [x] `Þm`
- [x] `ÞZ`
- [x] `Þ…`
- [x] `Þ↓`
- [x] `Þ↑`
- [x] `Þ×`
- [x] `ÞU`
- [x] `ÞF`
- [x] `Þ!`
- [x] `ÞD`
- [x] `ÞS`
- [x] `ÞṪ`
- [x] `Þ℅`
- [x] `Þ•`
- [x] `ÞṀ`
- [x] `ÞḊ`
- [x] `Þ/`
- [x] `Þ\`
- [x] `ÞR`
- [x] `ÞC`
- [x] `Þx`
- [x] `¨U`
- [x] `¨M`
- [x] `¨,`
- [x] `¨…`

**Comment by chunkybanana** [comment]
This list will be updated as I add more, for now it's all the list digraphs from #160

**Comment by Lyxal** [comment]
got'em.
