### ISSUE TITLE
`¨M` always casts `b` to an iterable

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#271]
Let's say you realized that `¨M` is awesome because it lets you apply a function to a certain index or list of indexes in a list. So you decide to use it to apply a function to the 10th element in a list. Well now there's a problem. The 10 gets cast to an iterable, and suddenly the function is being applied to the 0th and 1st elements in the list instead. Suddenly you have to ask OP if you can guarantee inputs be single digits, and the OP says no, and now you got gamed on, nerd.

Example: [Try it Online!](https://lyxal.pythonanywhere.com?flags=&code=10%20%CE%BB1%2B%3B%20%C2%A8M&inputs=%5B5%2C5%2C5%2C5%2C5%2C5%2C5%2C5%2C5%2C5%2C5%2C5%2C5%2C5%2C5%5D&header=&footer=)

**Comment by Lyxal** [comment]
Wrap `b` in a list idiot.

[Try it Online!](https://lyxal.pythonanywhere.com?flags=&code=10w%20%CE%BB1%2B%3B%20%C2%A8M&inputs=%5B5%2C5%2C5%2C5%2C5%2C5%2C5%2C5%2C5%2C5%2C5%2C5%2C5%2C5%2C5%5D&header=&footer=)

**Comment by AMiller42** [comment]
That costs extra bytes idiot.

**Comment by Lyxal** [comment]
yeah but it makes it valid stoopid.

**Comment by AMiller42** [comment]
yeah but it shouldn’t cast ints to iterables stoopid.

**Comment by Lyxal** [comment]
can't be a bug if it'sn't implemented

**Comment by Lyxal** [comment]
FiXeD
