### ISSUE TITLE
Vectorised print commands not disabling implicit output

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#28]
When using the `v` command to vectorise print commands, the print commands do not disable implicit output.

Example: [Try it Online!](http://lyxal.pythonanywhere.com?flags=&code=%E2%9F%A8%60Hello%2C%60%7C%60World!%60%E2%9F%A9v%2C&inputs=&header=&footer=)

**Comment by Lyxal** [comment]
well dang.

**Comment by Lyxal** [comment]
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLin6hgSGVsbG8sYHxgV29ybGQhYOKfqXYsIiwiIiwiIl0=)

**Comment by AMiller42** [comment]
It looks like this is actually a different issue. If you use `O` to disable the implicit output, nothing gets printed. [Try it Online!](https://vyxal.pythonanywhere.com/#WyJPIiwiIiwi4p+oYEhlbGxvLGB8YFdvcmxkIWDin6l2LCIsIiIsIiJd) If you then add an extra `,` after the vectorised print, it prints the same unexpected output, so it looks like the vectorised printing is actually modifying the list somehow. [Try it Online!](https://vyxal.pythonanywhere.com/#WyJPIiwiIiwi4p+oYEhlbGxvLGB8YFdvcmxkIWDin6l2LCAsIiwiIiwiIl0=)

**Comment by Lyxal** [comment]
This is a bigger issue than just vectorised printing.
