### ISSUE TITLE
`I` doesn't work properly on lists

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#312]
When splitting a list in half, the last half of the list is discarded and replaced with an empty list.

Example: [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLigoDKgEkiLCIiLCIiXQ==)

**Comment by razetime** [comment]
This is the element definition: https://github.com/Vyxal/Vyxal/blob/main/vyxal/elements.py#L1643

But the problem doesn't seem to be with the function. It calls https://github.com/Vyxal/Vyxal/blob/main/vyxal/elements.py#L1415 and that's what is doing the slicing. We can temporarily fix this with simple slice notation, but `index()` which feeds into the `i` builtin will be the proper long term solution.

**Comment by Lyxal** [comment]
Btw this is a problem with LazyLists, not the indexing

**Comment by Lyxal** [comment]
https://github.com/Vyxal/Vyxal/blob/main/vyxal/LazyList.py#L53
