### ISSUE TITLE
Mold modifies inputs

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#363]
When one of the arguments passed to Mold is input, whether taken implicitly or explicitly, it permanently modifies that input to be whatever the output of the Mold command was.

Examples:

[1 Input](https://vyxal.pythonanywhere.com/#WyIiLCIiLCI/LD8sIMK2LCDin6hcXGF8XFxifFxcY+KfqT8g4oCiID8sPywiLCIiLCJbMSwyLDMsNCw1LDYsNyw4LDldIl0=)

[2 Inputs](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLigKIgwrkswrkswrksIiwiIiwiWzEsMiwzLDQsNSw2LDcsOCw5XVxuWydhJywgJ2InLCAnYyddIl0=)

**Comment by AMiller42** [comment]
I was going to make this it's own issue, but after further investigation, it seems to stem from this issue: If a list is molded to the size of a smaller list, and the larger list came from input, then instead of modifying that input to be smaller, it moves the part that should be removed to the front of the inputted list.

Example: [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLin6gxfDJ8M+KfqSDigKIgPywiLCIiLCJbMSwyLDMsNCw1LDYsNiw3LDgsOV0iXQ==)

**Comment by chunkybanana** [comment]
High priority, we should not be mutating stuff.
