### ISSUE TITLE
Sorting floats is no.

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#365]
just no.

Floats ending in an even number: [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCI4NTQuMiBzIOKMiixcbjY5LjggcyDijIosXG40MjAuMDI0IHMg4oyKLFxuMTIzLjggcyDijIosXG4xLjIwIHMg4oyKLFxuMS4yMiBzIOKMiixcbjEuMjQgcyDijIosIiwiIiwiIl0=)

Floats ending in an odd number: [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCI4NTQuMSBzIOKMiixcbjY5LjkgcyDijIosXG40MjAuMDIzIHMg4oyKLFxuMTIzLjcgcyDijIosXG4xLjIxIHMg4oyKLFxuMS4yMyBzIOKMiixcbjEuMjUgcyDijIosIiwiIiwiIl0=)

bruh wtf is this

**Comment by Lyxal** [comment]
Looks like it's working as intended - it sorts the numerator and the denominator and leaves them in place.
