### ISSUE TITLE
Variable destructuring

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#385]

**Comment by chunkybanana** [comment]
Oops pressed enter gimme a moment to write up how this is going to work

**Comment by chunkybanana** [comment]
Basically, something like `→⟨x|y⟩`  would store the first of a value to x + the second to y. `(⟨x|y⟩|` would loop over something storing its first value as `x|y`. (I guess we could do the same with `←`)

**Comment by Lyxal** [comment]
How about something like `¨→x|y` instead?

**Comment by Lyxal** [comment]
also, the correct term is variable unpacking

**Comment by pxeger** [comment]
unpacking is no more or less correct than destructuring; it just depends on what your favourite language's documentation decides to call it

**Comment by razetime** [comment]
hm this requires some strong pattern matching

**Comment by cgccuser** [comment]
If and when we implement this, I'd like to take part in it. Pattern matching is cool, though not something we need to worry about much rn
