### ISSUE TITLE
Commands using the stack break with modifiers

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#415]
Commands that operate on some portion of the stack instead of popping from the stack (e.g. `W`, `!`, `^`, etc.) will operate on an empty stack when given modifiers such as `~₌₍`. The exceptions are the `„‟` commands, which just error instead, and the `v` modifier, which errors for any of the tested commands.

Example: [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIxIDIgMyA0IDUgNiB+XiBXLFxuMSAyIDMgNCA1IDYgflcgVyxcbjEgMiAzIDQgNSA2IH4hIFcsXG4xIDIgMyA0IDUgNiDigo3IriEgVyxcbjEgMiAzIDQgNSA2IOKCjF5XIFcsXG4xIDIgMyA0IDUgNiB+4oCeIFcsIiwiIiwiIl0=)

**Comment by Lyxal** [comment]
That's gonna need a kinda rethinking of how modifiers work: currently, modifiers just get the arity of the command they're modifying and pop that many arguments. `!`, `W` and `^` all have arity of `0` meaning nothing is popped. Maybe they could have a special arity `-1` to indicate they take the whole stack and modifiers would then know to pop everything based on that.

**Comment by AMiller42** [comment]
A potentially useful side effect of this might be that you can use `-1` as the arity for a lambda, which would make the lambda take the whole stack.
