### ISSUE TITLE
`Þ↑` is broken

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#445]

**Comment by pxeger** [comment]
demo?

**Comment by chunkybanana** [comment]
# [Vyxal](https://github.com/Vyxal/Vyxal), 27 bytes
```
⟨⟨1|2⟩|⟨3|1|5⟩|⟨2|4|9⟩⟩⁽∑Þ↑
```
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLin6jin6gxfDLin6l84p+oM3wxfDXin6l84p+oMnw0fDnin6nin6nigb3iiJHDnuKGkSIsIiIsIiJd)
