### ISSUE TITLE
Molding lists wraps the elements

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#460]
When you use `•` to mold one list to the shape of the other, it wraps each individual element in the process.

Example: [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLigKIiLCIiLCJbMSwgMiwgMywgNCwgNV1cbls2LCA3LCA4LCA5XSJd)

**Comment by razetime** [comment]
Honestly this "shape" idea is not well-defined. One idea  is to put the depth-1 into the structure of the other.
