### ISSUE TITLE
Add HTML tags to the short dictionary

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#473]
Since we now have a flag for rendering the output as HTML, we should include common HTML tags in the short dictionary for easy use in constructing our HTML output.

Examples include:
```
<h1>
<br>
<p>
<div>
<a>
```
As well as the corresponding closing tags. Obviously, this is not a complete list, but it's a start.

**Comment by pxeger** [comment]
more useful suggestions (based on some quick searching for HTML answers on CGCC):
```
<body>
<svg>
<style>
<script>
```

**Comment by pxeger** [comment]
FIxed by d1fe3f1683edc1cd9d82111c32899a31c935803f
