### ISSUE TITLE
Give a warning when rendered HTML contains `<script>` tags

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#476]
There's currently a warning given when using the `E` flag saying that users should be certain that the code they are running is legit. There should be a similar warning when using the `Ḣ` flag if the output contains the `<script>` tag.

**Comment by pxeger** [comment]
The HTML executes in an `<iframe>`, so this shouldn't be a problem. The only reason I added a warning for `E` was because I couldn't work out how to easily get the code to execute in an `<iframe>`.

sidenote: this is also definitely not difficulty:easy. That's why I sandboxed it!
