### ISSUE TITLE
Escaping bad

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#479]
Escaping bad.

`` `\\` `` should return `\`, [but it don't.](https://vyxal.pythonanywhere.com/#WyIiLCIiLCJgXFxcXGAiLCIiLCIiXQ==)

`` `\\n` `` should return `\n`, [but it don't.](https://vyxal.pythonanywhere.com/#WyIiLCIiLCJgXFxcXG5gIiwiIiwiIl0=)

Each backslash escapes the next character, even if it is being escaped itself. Fix it.

**Comment by Lyxal** [comment]
It's not parsing it's in the transpiling
