### ISSUE TITLE
Vertical tab escaping

### ISSUE THREAD

**Issue by TheSecondComing123** [Vyxal/Vyxal#480]
Look at [this](https://vyxal.pythonanywhere.com/#WyIiLCIiLCJcXFxcdiIsIiIsIiJd) program:

```
\\v
```

This outputs this error:

```
Traceback (most recent call last):
  File "/home/Vyxal/mysite/vyxal/main.py", line 131, in execute_vyxal
    code = transpile(code, ctx.dictionary_compression)
  File "/home/Vyxal/mysite/vyxal/transpile.py", line 40, in transpile
    vyxal.parse.parse(vyxal.lexer.tokenise(program)),
  File "/home/Vyxal/mysite/vyxal/parse.py", line 235, in parse
    structure.MonadicModifier(head.value, remaining[0])
IndexError: list index out of range
```

However, the expected output is

```
\v
```

Please fix.

**Comment by AMiller42** [comment]
https://chat.stackexchange.com/transcript/message/59959176#59959176

**Comment by cgccuser** [comment]
@AMiller42 I think having the interpreter crash with such a weird error should be considered a bug. We should add a friendlier error message.

**Comment by Lyxal** [comment]
> @AMiller42 I think having the interpreter crash with such a weird error should be considered a bug. We should add a friendlier error message.

I mean, the parser could just know to ignore empty modifiers.

**Comment by Lyxal** [comment]
Dang actually I'mma go do that
