### ISSUE TITLE
Use poetry instead of setuptools

### ISSUE THREAD

**Issue by pxeger** [Vyxal/Vyxal#482]
<s>Note the `s`

Really we should either:

- make `setup.py` use the dependencies from `requirements.txt`
- remove `requirements.txt` and force the use of `setup.py`
</s>

**Comment by cgccuser** [comment]
If we remove requirements.txt, what could we use instead of `pip install -r`?

**Comment by pxeger** [comment]
Use `pip install -e .` instead of `pip install -r requirements.txt`, which is how you're supposed to do it if you're using `setuptools`. (Or we could switch to using something like [poetry](https://python-poetry.org) which is simpler and better than `setuptools` IMO)

**Comment by pxeger** [comment]
https://chat.stackexchange.com/transcript/message/59960804#59960804
