### ISSUE TITLE
Base-255 compression trims leading `a`s

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#515]
When compressing a string using `øc`, or base-255 compression, any leading `a`s in the string are removed from the resulting string.

Example: [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCJgcmlja3JvbGxgw7hjOiwgYGFhYWFhYWFhYWFhYWFhYWFyaWNrcm9sbGDDuGM6LCA9LCIsIiIsIiJd)

**Comment by chunkybanana** [comment]
This... should not be happening. The base-255 compression  alphabet should be changed to start with ` `.
