### ISSUE TITLE
`%` should do format on (string,number)

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#518]
# [Vyxal](https://github.com/Vyxal/Vyxal), 33 bytes
```
`Hi I'm Bob, I'm % years old` 5 %
```
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCJgSGkgSSdtIEJvYiwgSSdtICUgeWVhcnMgb2xkYCA1ICUiLCIiLCJbMSwyLDMsNCw1XSJd)

Should do `"Hi I'm Bob, I'm 5 years old"`

**Comment by pxeger** [comment]
`%` is already supposed to do exactly this: 

https://github.com/Vyxal/Vyxal/blob/29e1b81a91e8c1a127976c68aa366c7a42993ed5/vyxal/elements.py#L2139-L2144

https://github.com/Vyxal/Vyxal/blob/29e1b81a91e8c1a127976c68aa366c7a42993ed5/vyxal/helpers.py#L149

It must just not be working.

**Comment by pxeger** [comment]
@Lyxal how is this not a bug?

**Comment by Lyxal** [comment]
(num, str) -> (b split into a equal pieces)[-1] 
     (str, num) -> (a split into b equal pieces)[-1]

**Comment by Lyxal** [comment]
@chunkybanana is suggesting to change the current overload to something more useful.

**Comment by pxeger** [comment]
Oh I'm dumb, you're talking about formatting with numbers, not strings
