### ISSUE TITLE
Different  syntax for comments

### ISSUE THREAD

**Issue by Fmbalbuena** [Vyxal/Vyxal#521]
Can you change because a space is NOP. You don't need two spaces!

**Comment by chunkybanana** [comment]
No for so many reasons.

**Comment by Fmbalbuena** [comment]
@chunkybanana  Oh, sorry

**Comment by pxeger** [comment]
FWIW, I'm in agreement that having one of only 256 available single characters be a comment is quite a waste golfing-wise. Using two spaces isn't the ideal solution though. My personal suggestion would be just to use a character outside the code page (and forcing a Unicode encoding) but which is generally fairly easy to type, so you can use it temporarily while testing programs but remove in final golfed code so it can still be counted in SBCS.

**Comment by Lyxal** [comment]
I think that pxeger's idea is a good compromise.

**Comment by razetime** [comment]
I was talking about doing the same for rickroll and amogus as well.

**Comment by pxeger** [comment]
Reopening since this seems at least considering

**Comment by cgccuser** [comment]
I like @pxeger's suggestion, but instead of using a different character for comments, let's continue `#` and merely move it out of the codepage. That way, old programs will still be valid, but anyone using comments will be forced to use UTF-8, which is fine because if they're using comments, they don't care about byte count anyway. We could add a different character like `⍝` to the codepage in place of `#`.

**Comment by AMiller42** [comment]
> I like @pxeger's suggestion, but instead of using a different character for comments, let's continue using `#` and merely move it out of the codepage.

If we did that, then any time somebody wanted to use `#` in e.g. a string or something, then they would have to use UTF-8. I don't think we should move any of the ASCII characters. At the moment their indexes in the codepage correspond with their ASCII values, and it should remain that way.

**Comment by cgccuser** [comment]
True, I didn't think of that.

**Comment by SE-Nitro** [comment]
What if we made comment a digraph? `¨`("other digraphs") only has 8 elements, for example.

**Comment by Lyxal** [comment]
This is implemented in version 3
