### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by Vyxal-Bot-old** [Vyxal/Vyxal#529]
basically Vyxals using pythons default error messaging and it'll help a lot if we change those to be more understandable

(created by mathcat [here](https://chat.stackexchange.com/transcript/message/60000262))

**Comment by cgccuser** [comment]
We need to check the type of all the arguments in functions that don't have overloads for some types and print out friendlier error messages using that.

**Comment by PyGamer0** [comment]
I fully support this.

(To make it even harder, lets implement rust's error messages ;P)

**Comment by razetime** [comment]
the ideal scenario would be to have no errors, and only weird behaviour, which often suits golfing.

**Comment by Tams-Tams** [comment]
@razetime weird behaviour?

**Comment by cgccuser** [comment]
@razetime I can get behind weird behaviors accompanied by warnings on stderr

**Comment by GingerIndustries** [comment]
@razetime  Just run each character in the error message through the SBCS and execute that! :p
