### ISSUE TITLE
`c` doesn't do substring matching

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#530]
# [Vyxal](https://github.com/Vyxal/Vyxal), 14 bytes
```
`Hello` `lo` c
```
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCJgSGVsbG9gIGBsb2AgYyIsIiIsIiJd)

**Comment by pxeger** [comment]
It works with individual characters, so it's just not doing substring matching. I think we probably want that, but it's not a bug because as specified currently it looks like it's only supposed to do individual elements. (`'lo'` is not an element of `'H', 'e', 'l', 'l', 'o'`)
