### ISSUE TITLE
Rearrange at indices  builtin

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#537]
Something like (list, function, indices) ->  
```
newvals = function(map(lambda a:list[a], indices))
for i in range(len(indices)):
  list[indices[i]] = newvals[i]
```

**Comment by cgccuser** [comment]
APL has `@` which is kinda like this

**Comment by PyGamer0** [comment]
I think Jelly has something similar.

**Comment by razetime** [comment]
this fits a generalized primitive, which is apply at indices, which fits another generalized primitive which is called Under. apply at indices seems like a decent fit for golfing.

**Comment by Lyxal** [comment]
`¨M` already does something like this.

**Comment by chunkybanana** [comment]
> `¨M` already does something like this.

No it really doesn't.

**Comment by Lyxal** [comment]
What type is `indices`? Also,

```
map(indices,lambda a:list[a])
```

isn't how `map` works. It takes lambda then iterable.

**Comment by Lyxal** [comment]
And if you had to give a one line description of what this does, what would it be?

@chunkybanana for this and the above.

**Comment by chunkybanana** [comment]
Indices is an integer list, I guess? I'm bad at python.

"Call a function on all elements at specified indices together and put that back in the list"?

BTW, this should be 1 byte because it's a function element and we have the space.

**Comment by Lyxal** [comment]
Of course, it's going to be an overload of `¢`
