### ISSUE TITLE
Rickrolling in local system

### ISSUE THREAD

**Issue by SE-Nitro** [Vyxal/Vyxal#543]
Currently, the program "lyxal" doesn't open Never Gonna Give You Up as it does in the online interpreter.
Idk if it's needed, would be cool though.
![image](https://user-images.githubusercontent.com/63205558/147696917-dbbcad67-f44d-4c78-b49f-22f74b49c713.png)

**Comment by cgccuser** [comment]
How would you even expect this to be implemented? Would you like to embed YouTube videos in your terminal?

**Comment by Tams-Tams** [comment]
Uh open a browser tab

**Comment by pxeger** [comment]
```
import webbrowser
webbrower.open("https://www.youtube.com/watch?v=dQw4w9WgXcQ")
```

**Comment by edison1119** [comment]
```
import os
os.system(“start https://www.youtube.com/watch?v=dQw4w9WgXcQ”)
```

**Comment by PyGamer0** [comment]
@edison1119 i dont think that works cross platform

**Comment by edison1119** [comment]
how do we open web on prompt only systems(how does it react)?

**Comment by pxeger** [comment]
The Python `webbrowser.open` function returns a boolean indicating the success status of opening the URL, so if it doesn't work nothing bad will happen. If opening the rickroll fails, that should just be ignored.

**Comment by Lyxal** [comment]
There was a script once upon a time that rickrolled you in the terminal. Maybe that could be used?

**Comment by Lyxal** [comment]
nvm it's unix/linux only

https://github.com/keroserene/rickrollrc/

**Comment by cgccuser** [comment]
I mean, you could use Cygwin for it

**Comment by cgccuser** [comment]
@razetime priority:high?

**Comment by RedwolfPrograms** [comment]
Would it be possible to have it print a rickroll as text in the terminal? You could print the lines with the correct timing from the song, even. But I feel like opening a browser tab would seem a little...idk, intrusive?

**Comment by dloscutoff** [comment]
On the contrary: opening a browser tab is exactly the expected amount of intrusive for a Rickroll (and it's got precedent in Python's `import antigravity`). ;^) But for systems that don't have web browsers, printing the text in the terminal seems like a sensible fallback behavior.

**Comment by Tams-Tams** [comment]
@dloscutoff Yeah sounds like a good solution

**Comment by Lyxal** [comment]
This seems like it was a haha funny joke for a bit, but it doesn't seem to have had much traction. Open this if you want to implement it.
