### ISSUE TITLE
`__gt__`, `__lt__`, etc aren't defined for lazylists

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#549]
What it says on the title. This means lazylists can't be normally compared which can cause problems when, say, sorting by lazylists.

**Comment by cgccuser** [comment]
We have a custom sort, don't we?

**Comment by pxeger** [comment]
this may help:

https://github.com/pxeger/libgolf/blob/224342e3b05e8610085a1f9d1b05177cc32cb5f1/libgolf/list.py#L180

**Comment by chunkybanana** [comment]
Because sorting by lazylists is *still* broken and this seems like the best way to fix it.
