### ISSUE TITLE
Add regression tests for past bugs

### ISSUE THREAD

**Issue by cgccuser** [Vyxal/Vyxal#561]
We should really add an extra test every time a bug is fixed just to make sure that bug doesn't pop up again.

**Comment by razetime** [comment]
would be worth listing the bugs which were omitted here. how long back do we plan on checking?

**Comment by pxeger** [comment]
I suggest a total rewrite with full testing from the beginning ;)

**Comment by chunkybanana** [comment]
Gonna make a start on this. I'm working on issues posted from late July 2021 onwards.

**Comment by chunkybanana** [comment]
After some thought, this is only necessary for issues where:

- It doesn't need a sanity check (e.g. #209 or #287)
- The corresponding element tests wouldn't fail
- It's relevant to v2.6+
