### ISSUE TITLE
`ṅ` errors on integers

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#565]
# [Vyxal](https://github.com/Vyxal/Vyxal), 2 bytes
```
5ṅ
```
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCI14bmFIiwiIiwiM1xuNSJd)

**Comment by chunkybanana** [comment]
Should do nothing, until we think of something for it to do

**Comment by cgccuser** [comment]
This is kind of a bug, because the element description says that it works for `any a`, which means it should also join numbers on an empty string (which I assume would mean that it's like `str(x)` for numbers).

**Comment by Lyxal** [comment]
So uh turns out it has an undocumented changed overload for numbers...

```
(num) -> abs(a) <= 1
```
