### ISSUE TITLE
All lists builtin

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#573]
Given a list, get all lists within it. For example, [1,2,[3,[4,5],6],7] -> [1,2,[3,[4,5],6],7], [3,[4,5],6], [4,5]

Should be versions including + not including original list.

**Comment by chunkybanana** [comment]
Ssh totally not cheating on [this](https://codegolf.stackexchange.com/questions/240673/find-the-maximum-length-in-a-ragged-list)

**Comment by cgccuser** [comment]
I think we might be able to make a more general builtin to find (contiguous) sublists according to a predicate

**Comment by razetime** [comment]
that would be cool, but this request is for a recursive find. It might be worth a higher order function, although I don't really see the use of it. More importantly, you can't answer that challenge since the builtin would have been technically been made for it.

**Comment by Lyxal** [comment]
Is this still something that's wanted, or has the request changed altogether?

**Comment by edison1119** [comment]
Should this work with infinity list or not? I think making it work on infinite list would be very hard.

**Comment by Lyxal** [comment]
> Is this still something that's wanted, or has the request changed altogether?
@chunkybanana

**Comment by chunkybanana** [comment]
I think a general recursion builtin would be better than this, so I'll close it.
