### ISSUE TITLE
Some nilads don't vectorise nicely

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#579]
# [Vyxal](https://github.com/Vyxal/Vyxal), 7 bytes
```
123fvkd
```
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIxMjNmdmtkIiwiIiwiIl0=)

**Comment by cgccuser** [comment]
What's the expected result? `⟨ 0123456789 | 0123456789 | 0123456789 ⟩`?

**Comment by chunkybanana** [comment]
Yes

**Comment by AMiller42** [comment]
Cause: https://chat.stackexchange.com/transcript/message/60276081#60276081

Relevant code: https://github.com/Vyxal/Vyxal/blob/main/vyxal/elements.py#L5123
