### ISSUE TITLE
Builtins that need infinite list support

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#586]
- [x] #585
- [x] #598
- [x] #599
- [x] #600
- [x] #601
- [x] #602
- [x] #603
- [x] #604
- [x] [`ḣ`](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLigb3igLogMSDhuJ4g4bijIiwiIiwiIl0=) (head extract)
- [x] [`y`](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLigb3igLogMSDhuJ4geSIsIiIsIiJd) (uninterleave)
- [x] [`Y`](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLigb3igLox4bieIOKBveKHpzHhuJ4gWSIsIiIsIiJd) (interleave)
- [x] [`Þf`](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLigb3igLogMSA1cncg4bieIMOeZiIsIiIsIiJd) (shallow flatten)
- [x] #655
- [x] [`ṗ`](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLigb3igLogMSDhuJ4g4bmXIiwiIiwiIl0=) (powerset)
- [x] [`ẇ`](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLigb3igLogMSDhuJ4gMyDhuociLCIiLCIiXQ==) (chunks)
- [x] [`Ġ`](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLigb3igLogMSDhuJ4gwr0g4oyKIMSgIiwiIiwiIl0=) (group run lengths, possibly?)
- [x] [`ȯ`](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLigb3igLox4bieIDIwIMivIiwiIiwiIl0=) (a[b:], positive indices only)
- [x] [`Ḟ`](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLigb3igLox4bieIDQg4bieIiwiIiwiIl0=) (every ath item of b)
- [x] [`Þs`](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLigb3igLox4bieIDQgw55zIiwiIiwiIl0=) (slices of a skipping b items)
- [x] [`h`](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLDnuKIniBoIiwiIiwiIl0=) (head)
- [x] [`¯`](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLDnuKIniDCryIsIiIsIiJd) (deltas)
- [x] [`≈`](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLDnuKIniDiiYgiLCIiLCIiXQ==) (all equal?)
- [x] #699
- [x] #726

**Comment by pxeger** [comment]
set xor can't work on infinite lazy lists

**Comment by chunkybanana** [comment]
> set xor can't work on infinite lazy lists

Oh. Oops
