### ISSUE TITLE
`F` (filter) doesn't work on infinite lazylists

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#600]
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLigb3igLox4bieIOKBveKHpzHhuJ4gRiIsIiIsIiJd) Second is the odd numbers.

**Comment by cgccuser** [comment]
How would this work on infinite lazylists anyway? (unless you assumed `rhs` were sorted)
