### ISSUE TITLE
Looping over the ghost variable is broken

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#617]
# [Vyxal](https://github.com/Vyxal/Vyxal), 8 bytes
```
13 (| ←,
```
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIxMyAofCDihpAsIiwiIiwiIl0=)

**Comment by razetime** [comment]
what exactly should this be doing?

**Comment by pxeger** [comment]
Who are you, Rupert Murdoch? (I changed the title to be more sensible)

**Comment by AMiller42** [comment]
This is because the loop is saving to the variable `VAR_` aka the ghost variable, but at some point the ghost variable was changed to be `ctx.ghost_variable`. I'm guessing that change was probably made when the ghost variable was made global.
