### ISSUE TITLE
`İ` doesn't use modular indexing

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#625]
# [Vyxal](https://github.com/Vyxal/Vyxal), 13 bytes
```
123f 12345f İ
```
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIxMjNmIDEyMzQ1ZiDEsCIsIiIsIiJd)

Should be [2,3,1,2,3]

**Comment by AMiller42** [comment]
I don’t know what changed, but this appears to be working now.
