### ISSUE TITLE
Not able to run Vyxal locally

### ISSUE THREAD

**Issue by Tams-Tams** [Vyxal/Vyxal#645]
`pip install -e .` gives the error:
```
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: []\Vyxal\Fork
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
```

Steps to reproduce:
1. Fork Vyxal (I think)
2. Clone with git
3. cd into directory 
4. run `pip install -e .`

**Comment by pxeger** [comment]
Was there documentation that said to use `pip install -e .`? If so, it's out of date and needs changing. You need to use poetry:

```
pip install --user poetry
poetry install
poetry run vyxal ...
```

Or if you don't plan to develop on vyxal, you can just install from PyPI instead of from git:
```
pip install --user vyxal
python -m vyxal ...
```

**Comment by Tams-Tams** [comment]
Ah, thanks.

**Comment by cgccuser** [comment]
We need to add this to the contributing guide too
