### ISSUE TITLE
`j` flag (and in general all output joining flags)

### ISSUE THREAD

**Issue by cgccuser** [Vyxal/Vyxal#655]
# [Vyxal](https://github.com/Vyxal/Vyxal) `j`, 7 bytes
```
⁽› 1 Ḟ 
```
[Try it Online!](https://vyxal.pythonanywhere.com/#WyJqIiwiIiwi4oG94oC6IDEg4bieICIsIiIsIiJd)

**Comment by Tams-Tams** [comment]
I'll try because I'm bored
