### ISSUE TITLE
Compressed strings sometimes break

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#659]
# [Vyxal](https://github.com/Vyxal/Vyxal), 5 bytes
```
«×Fṫ«
```
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLCq8OXRuG5q8KrIiwiIiwiIl0=)

Don't Ask Me Why ™

**Comment by AMiller42** [comment]
When decompressing the string, it is converted from base-255 to base-10, in this case resulting in `537950`. That number is then converted to base-27 to index into the lowercase+space alphabet. However, in this case the result is `[27, 8, 25, 2]`. As a result, when it tries to index into the alphabet of length 27, the index 27 doesn't exist, and it errors. When converting the base-10 number to base-27, the `to_base_digits` function is used.

I decided to try converting 64 to base-2, which should return `[1, 0, 0, 0, 0, 0, 0]`, but instead it returns `[2, 0, 0, 0, 0, 0]`. From looking at it, the solution should be as simple as changing `>` to `>=`.
