### ISSUE TITLE
Infinite lists need to be marked as so

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#670]
Builtins that take and return infinite lists need to mark their output as infinite. Currently, strip and possibly others have different behaviour on finite and infinite lists.

**Comment by Tams-Tams** [comment]
@chunkybanana What do you exactly mean by mark? In the markdown file?

**Comment by Lyxal** [comment]
> @chunkybanana What do you exactly mean by mark? In the markdown file?

LazyLists have an attribute that determines whether they're infinite or not. This is talking about setting that attribute on returned LazyLists if the input to a function contained an infinite lazylist

**Comment by Lyxal** [comment]
This seems to have been done.

**Comment by chunkybanana** [comment]
There's no way this has been done - [Try it Online!](https://vyxal.pythonanywhere.com/#WyI1IiwiIiwiw57iiJ4gM2xmIDTJvlAiLCIiLCIiXQ==)

The above code takes the infinite list of positive integers, gets runs of length 3, and flattens those.

`P` only strips from the front when given a known infinite list. If the given list was marked as infinite, stripping 1-4 from it would work, and terminate. Since it doesn't terminate, at least one (possibly both) builtins *are not* doing this.
