### ISSUE TITLE
Create list of length a filled with b

### ISSUE THREAD

**Issue by Tams-Tams** [Vyxal/Vyxal#673]
Idk if there's already an element for that, but IMO that'd be useful.
Example: `2 3f` would output `[3, 3]`

**Comment by chunkybanana** [comment]
# [Vyxal](https://github.com/Vyxal/Vyxal), 4 bytes
```
2 3ẋ
```
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIyIDPhuosiLCIiLCIiXQ==)

`ẋ`.

**Comment by Tams-Tams** [comment]
Oh, ok
