### ISSUE TITLE
Inputting `True` or `False` doesn't work properly

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#676]
If you input `True` or `False` in the online interpreter, it is evaluated as a `bool`. This doesn't error in and of itself, but it does error if you try to do anything with it, because the `vyxalify` function doesn't cast it properly. This shouldn't be too much of an issue, since we can just add a special case for `bool` values in the function.

Example: [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIxKyIsIiIsIlRydWUiXQ==)

**Comment by cgccuser** [comment]
How about a vote? If you want it to be turned into a string, respond with a thumbs up. If you want numbers, respond with a thumbs down.
