### ISSUE TITLE
`~` doesn't filter on monads

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#680]
# [Vyxal](https://github.com/Vyxal/Vyxal), 8 bytes
```
12345f~∷
```
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIxMjM0NWZ+4oi3IiwiIiwiIl0=)

**Comment by chunkybanana** [comment]
Also, what should it do with chained modifiers?
(IMO always filter, arity detection like that is a pain.

**Comment by chunkybanana** [comment]
Also, what should it do with triads / nilads?

**Comment by Lyxal** [comment]
Arities 3 and up should also not pop

Nilads is something that will require a bit of thinking

**Comment by Lyxal** [comment]
Chained stuff (modifiers) should act based on their arity. Because iirc they have their own arity

**Comment by AMiller42** [comment]
Obviously, on nilads it should execute without popping /s
