### ISSUE TITLE
Make K flag work better

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#689]
Specifically, it'd be nice to have it force I/O as codepoint lists

**Comment by Lyxal** [comment]
Well yes, but actually no.

There is no K flag anymore.

**Comment by cgccuser** [comment]
@Lyxal So...is this issue going to be closed?

**Comment by Lyxal** [comment]
Depends if the `K` flag is still wanted.

**Comment by Lyxal** [comment]
There's no `K` flag so this can be closed
