### ISSUE TITLE
`ḋ` doesn't work on infinite lists

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#699]
# [Vyxal](https://github.com/Vyxal/Vyxal), 4 bytes
```
Þp3ḋ
```
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLDnnAz4biLIiwiIiwiIl0=)

**Comment by Lyxal** [comment]
This is because `itertools.combinations` decides to take the `len`gth of its argument: https://docs.python.org/3/library/itertools.html#itertools.combinations
