### ISSUE TITLE
`⁋` Doesn't work on infinite lists

### ISSUE THREAD

**Issue by Fmbalbuena** [Vyxal/Vyxal#702]
# [Vyxal](https://github.com/Vyxal/Vyxal)
```
Þp⁋
```
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLDnnDigYsiLCIiLCIiXQ==)

Seriously I need this.

**Comment by chunkybanana** [comment]
This produces an infinite string which makes no sense in the context of Vyxal and can't be created in Python.

Use the j flag once that PR is done.
