### ISSUE TITLE
Sympy output rounds large integers

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#714]
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLCuzkwMjdwaiBmc2tnb25jaWlqa3cgYmlmdWprd25jZmtoandlcmhmamN3cmNmd8W8d2VjyK9jUWN4d2XihIVjeHdkwrsgNCAqIiwiIiwiIl0=)

**Comment by sporeball** [comment]
what value is expected here?

**Comment by pxeger** [comment]
554742894234135787943916131496041009930609457217361827795339018042312975993735628917869194048950881084294882429996601207629481513639882437972714156

**Comment by chunkybanana** [comment]
Append `S` to stringify the number and it'll work fine, it's just a random large number

**Comment by AMiller42** [comment]
This isn’t just an output thing, as it also affects some operations. For example, large numbers may be considered equal, even if they aren’t. Here’s an example where `(1e999)-1000 == (1e999)+1000`: [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCI5OTnihrUgMTAwMC1cbjk5OeKGtSAxMDAwK1xuPSIsIiIsIiJd)

**Comment by Lyxal** [comment]
@AMiller42 except it isn't. The outputting problem was due to how `sympy.N` works - it goes to significant figures instead of decimal places. The equality problem is due to how the comparison of numbers works.
