### ISSUE TITLE
`ÞẊ` (cartesian power) needs infinite list support

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#726]
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLDnuKInjPDnuG6iiIsIiIsIiJd)

TBH I have no idea how to do this. You need to basically create a bijection between ℕ and ℕ<sup>n</sup>. Good luck!

**Comment by Lyxal** [comment]
Easy, just cartesian product of a list with itself n - 2 times.
