### ISSUE TITLE
Bracketify Does not Work

### ISSUE THREAD

**Issue by Seggan** [Vyxal/Vyxal#728]
Simple. The bracketify element 'øB' does not work (at least in TIO it doesn't). Demonstration: https://vyxapedia.hyper-neutrino.xyz/tio#WyIiLCJcXHPDuEIiLCIiLCIiLCIiXQ==

**Comment by AMiller42** [comment]
The Vyxapedia site is running an old version of Vyxal (I believe it's somewhere around 2.4.2), which doesn't have the Bracketify command. You should use the current version, hosted at vyxal.pythonanywhere.com: [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCJcXHPDuEIiLCIiLCIiXQ==)

**Comment by Seggan** [comment]
Ah, ty
