### ISSUE TITLE
Diagraphs for checking sortedness

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#741]
We should have some diagraphs for checking various sortednesses. At the moment, just checking if a list/string is sorted requires 3 bytes: `:s=`. Having this as a diagraph would be nice, and while we're at it, I think we should add a few more. I think we should add diagraphs to check if a list/string:

- [ ] Is sorted, e.g. `[1,2,3] → 1` `[3,2,1] → 0` `[1,3,2] → 0`
- [ ] Is reverse sorted, e.g. `[1,2,3] → 0` `[3,2,1] → 1` `[1,3,2] → 0`
- [ ] Is either sorted/reverse sorted, e.g. `[1,2,3] → 1` `[3,2,1] → 1` `[1,3,2] → 0`
- [ ] Is unsorted, e.g. `[1,2,3] → 0` `[3,2,1] → 0` `[1,3,2] → 1`

Let me know if you need any elaboration. Feel free to propose similar diagraphs and I'll add them to the list.

**Comment by Lyxal** [comment]
Just on the "is unsorted" digraph - how would you define sorted? Because `[1, 3, 2]` could be considered sorted by some sort of ordering.

**Comment by AMiller42** [comment]
> Just on the "is unsorted" digraph - how would you define sorted? Because `[1, 3, 2]` could be considered sorted by some sort of ordering.

This is pretty much what I had in mind:

Sorted: `:s⁼`
Reverse Sorted: `:sṘ⁼`
Sorted/Reverse Sorted: `₌‡s⁼≬sṘ⁼∨`
Unsorted: `₌‡s⁼≬sṘ⁼∨¬`

**Comment by pxeger** [comment]
If there were a modifier for "is equal after applying", then an equivalent effect could be achieved, but with much a more general builtin.

**Comment by AMiller42** [comment]
> If there were a modifier for "is equal after applying", then an equivalent effect could be achieved, but with much a more general builtin.

I agree, this is probably a much better idea
