### ISSUE TITLE
Printed wrapped strings don't escape backslashes

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#746]
If you wrap a string and then print it, any backticks in the string are escaped with backslashes, but any backslashes aren't. Functionally, it doesn't affect anything, but it looks a bit strange when you compare the two.

Example: [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCJgIFxcXFwgYHcsXG5gIFxcYCBgdywiLCIiLCIiXQ==)

**Comment by cgccuser** [comment]
Do we want to escape even backticks?

**Comment by SE-Nitro** [comment]
For escaping backticks in a string, I'd say yes, unless there is another way of printing a single backtick.
