### ISSUE TITLE
Element for [n, -n, n, -n, ...]

### ISSUE THREAD

**Issue by TheSecondComing123** [Vyxal/Vyxal#768]
`<command>1` => `[1, -1, 1, -1, ...]`

**Comment by AMiller42** [comment]
Conversely, there should also be a command for `[-n, n, -n, n, ...]`.

**Comment by cgccuser** [comment]
@AMiller42 The second simply requires negating the first, I don't think it's worth another command

**Comment by cgccuser** [comment]
This can be done now by multiplying n by all multiples of -1. Do we need an element for this?

**Comment by Lyxal** [comment]
I don't think so
