### ISSUE TITLE
Explicit input with the `a` flag should act normally

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#769]
When using the `a` flag, you are only able to take input by taking the entire input list. This should be changed so that explicit input is taken normally when using the `a` flag, especially since there is already a command to take the full input list, namely `□`.

Example: [Try it Online!](https://vyxal.pythonanywhere.com/#WyJhIiwiIiwiLFxuPyxcbuKBsCxcbuKWoSwiLCIiLCIxXG4yXG4zXG40XG41Il0=)

**Comment by chunkybanana** [comment]
Forgot to close this when I fixed it, but it works now.
