### ISSUE TITLE
Counter for while loop

### ISSUE THREAD

**Issue by SE-Nitro** [Vyxal/Vyxal#776]
It would be nice to have a counter `n` for a while loop too.
[Try it online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIxe24sIiwiIiwiIl0=)
So it would print 1, 2, 3, 4, 5, ...
Currently, it requires [7 bytes (I think)](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIxwqN7wqXigKbigLrCoyIsIiIsIiJd)

**Comment by PyGamer0** [comment]
I think its already there....

**Comment by Seggan** [comment]
[4 bytes](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIxe+KApuKAuiIsIiIsIiJd)

**Comment by Seggan** [comment]
Also, I think it should start at 0

**Comment by AMiller42** [comment]
> [4 bytes](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIxe+KApuKAuiIsIiIsIiJd) Golfing even on Github 🤣

This is talking about being able to use `n` to retrieve the counter value at any time. Your program just prints and increments the ToS, which wouldn't work if anything got put on the stack during the loop: [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIxe+KApuKAuiBgUmlja2AiLCIiLCIiXQ==)

The example uses the register to simulate how `n` would work, being able to grab the value at any time. That being said, [5 bytes](https://vyxal.pythonanywhere.com/#WyIiLCIiLCJ7JuKAoeKAuuKApiIsIiIsIiJd).

**Comment by Seggan** [comment]
> Your program just prints and increments the ToS, which wouldn't work if anything got put on the stack during the loop
One of my Jyxal answers uses this exact strategy (that was v0.2.0), just with a `:`
