### ISSUE TITLE
`j` vectorises weirdly

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#781]
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLin6gg4p+oIGBoYCB8IGBlYCDin6kgfCDin6ggYGxgIHwgYGxgIHwgYG9gIOKfqSDin6kg4p+oIGBhYCB8IGBiYCDin6kgdmoiLCIiLCIiXQ==)

Don't ask me what's happening here. Seriously, don't.

**Comment by Lyxal** [comment]
Well what do you expect? `vj` isn't element-wise vectorisation - it's the equivalent of [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLin6gg4p+oIGBoYCB8IGBlYCDin6kg4p+oIGBhYCB8IGBiYCDin6kganwg4p+oIGBsYCB8IGBsYCB8IGBvYCDin6kg4p+oIGBhYCB8IGBiYCDin6kgaiDin6kiLCIiLCIiXQ==)

`Zvƒj` is what you're after. Getting that shorter is for a feature request, not a bug report.
