### ISSUE TITLE
`j` should have better behaviour on lists

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#782]

**Comment by chunkybanana** [comment]
# [Vyxal](https://github.com/Vyxal/Vyxal), 37 bytes
```
⟨ ⟨ 1 | 2 ⟩ | ⟨ 3 | 4 ⟩ ⟩ ⟨ 5 | 6 ⟩ j
```
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLin6gg4p+oIDEgfCAyIOKfqSB8IOKfqCAzIHwgNCDin6kg4p+pIOKfqCA1IHwgNiDin6kgaiIsIiIsIiJd)

Currently, this creates  a string, which is completely useless.

**Comment by Lyxal** [comment]
what about something like `⟨ 1 | 2 ⟩ ⟨ 5 | 6 ⟩ j`? or anything else where the lhs contains only scalars?

**Comment by SE-Nitro** [comment]
Maybe join by `56` like [this](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLin6gxfDLin6nin6g1fDbin6nhuYVqIiwiIiwiIl0=)?

**Comment by chunkybanana** [comment]
> what about something like `⟨ 1 | 2 ⟩ ⟨ 5 | 6 ⟩ j`? or anything else where the lhs contains only scalars? what should they do?

How about it inserts rhs between elements of lhs, then flattens the whole thing by one level?

**Comment by Steffan153** [comment]
I'd expect `⟨ ⟨ 1 | 2 ⟩ | ⟨ 3 | 4 ⟩ ⟩ ⟨ 5 | 6 ⟩ j` to return `[[1, 2], [5, 6], [3, 4]]`, and if `lhs` only contains scalars, same behavior. However, `[1, 2, 3] [5, 6] j` returning `[1, 5, 6, 2, 5, 6, 3]` (flattening) could also be useful. We could make that a digraph, though.
