### ISSUE TITLE
`Ȧ` and `Ṁ` should try to find an integer argument

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#783]
Currently `Ȧ` and `Ṁ` (assign + insert) require an integer in the second position. It'd be more versatile if they tried to find an integer argument instead of erroring.

**Comment by Lyxal** [comment]
`Ȧ` doesn't actually require an integer - strings are converted to a list of ordinals and lists have special functionality (which you requested lol). `Ṁ` will have the same functionality as `Ȧ` with lists.
