### ISSUE TITLE
Chained stack modifiers don't actually operate on the stack

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#790]
# [Vyxal](https://github.com/Vyxal/Vyxal), 12 bytes
```
3 4₌≬+:_≬+:_
```
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIzIDTigoziiawrOl/iiawrOl8iLCIiLCIiXQ==)

for example

This could be quite hard to fix, I don't really understand the internal structure of Vyxal's modifiers.

**Comment by chunkybanana** [comment]
Speaking of which, pretty sure modifier grouping isn't documented.

**Comment by Lyxal** [comment]
here's the thing:

```
3 4₌λ2|+:_;λ2|+:_;
```

does what I think you intend.

but so should 

```
3 4₌‡≬+:_d‡≬+:_d
```

but it doesn't

**Comment by Lyxal** [comment]
@chunkybanana about my above remark - what do you think?

**Comment by chunkybanana** [comment]
I agree that that should just push the function, not try and call it. 

Also, would setting the arity to len(stack) dynamically work?

**Comment by Lyxal** [comment]
You don't need to set it to `len(stack))` - setting it to `-1` should automatically use stack if that was actually implemented.

**Comment by Lyxal** [comment]
> Also, would setting the arity to len(stack) dynamically work?

On second thought, no, it wouldn't work. Because what happens if you try something like `₌+-` on an empty stack with two inputs? `len(stack)` will set the arity to `0` and not pop any inputs despite the fact that there needs to be stuff popped.
