### ISSUE TITLE
`øM` doesn't vectorise

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#794]
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLDuOG5gSIsIiIsIltcImEvYlwiLFwiYyhlfWZcIl0iXQ==) for example

**Comment by Lyxal** [comment]
You fool, you linked `øṁ`

**Comment by chunkybanana** [comment]
Oops. øM doesn't work anyway though.
