### ISSUE TITLE
Better matrix / graph builtins

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#807]
Specifically:

- [x] Matrix exponentiation
Repeated multiplication of the matrix with itself
- [x] Identity matrix of size n
A matrix with 1s on the main diagonal and zeroes elsewhere
E.g. for 3
```
[ [1, 0, 0],
  [0, 1, 0],
  [0, 0, 1] ]
```
- [x] Graph adjacency matrix
Take a graph of the form `[[1,3],[2,4],[3,4]]` and create an adjacency matrix e.g. for this,
```
[ [0, 0, 1, 0],
  [0, 0, 0, 1],
  [1, 0, 0, 1],
  [0, 1, 1, 0] ]
```
- [x] Graph distance matrix
Take a graph of the form `[[1,3],[2,4],[3,4]]` and create a distance matrix, e.g. for the above,
```
[ [0, 3, 1, 2],
  [3, 0, 2, 1],
  [1, 2, 0, 1],
  [2, 1, 1, 0] ]
```

**Comment by Lyxal** [comment]
I'mma gon need some examples and descriptions of what these do.

**Comment by chunkybanana** [comment]
Information added.

**Comment by PyGamer0** [comment]
> Graph adjacency matrix

Did you just yoink the test case from my challenge lol?

**Comment by Lyxal** [comment]
For matrix exponentiation, wouldn't `e` just work? Or am I missing something?

**Comment by Lyxal** [comment]
Also, someone else might have to do the graph stuff - I don't know much about graph theory at all (s/much/anything)

**Comment by chunkybanana** [comment]
Pretty sure it doesn't because it's repeated matrix multiplication.

**Comment by cgccuser** [comment]
I guess we'll need one set of builtins for undirected graphs and one for directed graphs.
