### ISSUE TITLE
Image digraph

### ISSUE THREAD

**Issue by SE-Nitro** [Vyxal/Vyxal#809]
Should we have a digraph that can create and edit images? Like creating a blank image, drawing a shape on it, etc.
## Elements
- create a blank image with width/height, return an image object
- draw a rectangle on an image object, given positions, and size
- draw a circle on an image object, given positions, and radius
- draw a line on an image object, given start, and end-coordinates
- display imazge
- save image object (only when run locally)

**Comment by cgccuser** [comment]
I don't think these are useful except in some very specific circumstances, and evaling as Python (or whatever the host language is) should let you do it anyway.

**Comment by SE-Nitro** [comment]
@cgccuser Yeah, true, forgot about eval (close?)

**Comment by SE-Nitro** [comment]
closing it unless someone wants to implement it
