### ISSUE TITLE
Ragged list recursion structure

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#814]
Pretty much, a structure that calls itself on lists, then does something to the result, and returns scalars on their own. Maybe with a second branch, it could return / operate on scalars with that?

For example, `¨r∑` would be equivalent to`λIȧ[vx∑` - recursively calling on each for lists, and returning scalars normally, then summing the result. 
`¨r∑|1` would be equivalent to `λIȧ[vx∑|1`, recursively calling on each for lists then summing, and replacing scalars with 1.

**Comment by Lyxal** [comment]
I kind of understand what you mean, but I might need a few examples to solidify what it is you're requesting.
