### ISSUE TITLE
`g` and `G` flatten a list

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#815]
When passed a multidimensional list, these two builtins flatten the list first. I think it would make more sense for it to do lexicographic comparison. Onions?

**Comment by Lyxal** [comment]
Sure. I like this.

**Comment by PyGamer0** [comment]
I want to try doing this

**Comment by chunkybanana** [comment]
We don't need a digraph to get the min/max of the flattened form - `fg` and `fG`

**Comment by cgccuser** [comment]
I'm an idiot, I thought you meant you *wanted* them to flatten lists. +1 from me
