### ISSUE TITLE
Add Apply at Index(cies) Element

### ISSUE THREAD

**Issue by Seggan** [Vyxal/Vyxal#822]
Something like:
`lst a, lst b, fun c: [c(n) if i in b else n for n, i in enumerate(a)]`
`lst a, num b, fun c: a[b] = c(a[b])`

**Comment by Seggan** [comment]
I though I saw this one somewhere... but I can't find it now

**Comment by Lyxal** [comment]
`¨M`?

I ask because it may not be the same as what you're requesting. Tell me if it isn't and I'll implement it.

**Comment by Seggan** [comment]
Yep, it is exaclt what I'm thinking of. Let's add a `lst a, num b, fun c` overload so we don't have to spend an extra byte on `<num>w`

**Comment by Lyxal** [comment]
We can do that.

I'll get around to it soon.

**Comment by Lyxal** [comment]
Turns out it already wraps numbers.

So this is more a documentation change.
