### ISSUE TITLE
Make lists immutable

### ISSUE THREAD

**Issue by cgccuser** [Vyxal/Vyxal#833]
Jyxal already does this and it'd make implementing copying and stuff way easier. This *would* break answers that duplicate a list, modify it in one place, and expect the other copy to have those modifications, but there are <=11 such answers, so it should be fine. It's well worth the reduction in `LazyList` bugs and simplicity.

**Comment by Lyxal** [comment]
So just to be clear - this is just removing the `__setitem__` method of `LazyList` and fixing functions that assign stuff to lists (which can be found with the regex `\[.*\] = `)?

**Comment by cgccuser** [comment]
@Lyxal yes
