### ISSUE TITLE
regex replace fails on numbers

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#877]
https://vyxal.pythonanywhere.com/#WyJEIiwiIiwiYFtBLVpdYCTOuzQ7w7jhuZlcblxuIiwiIiwiSGVsbG8sIFdvcmxkISJd

**Comment by Seggan** [comment]
should be a simple `str()` call

**Comment by Steffan153** [comment]
it's only with the lambda syntax, not if you just straight out replace
