### ISSUE TITLE
`ẇ` returns an extra empty string when there's nothing to split

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#878]
https://vyxal.pythonanywhere.com/#WyIiLCIiLCJgSGVsbG9gIGB4YCDhuociLCIiLCIiXQ==

**Comment by chunkybanana** [comment]
It also doesn't return a leading empty string when splitting on the first character

**Comment by Steffan153** [comment]
> It also doesn't return a leading empty string when splitting on the first character

![image](https://user-images.githubusercontent.com/40404519/164345504-1bd3a9d6-fc51-4365-8c64-ef4704f84fcf.png)
