### ISSUE TITLE
`¨£` (starmap) doesn't show up in `parsed_yaml.js`

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#880]

**Comment by Steffan153** [comment]
Yeah it does
https://github.com/Vyxal/Vyxal/blob/main/documents/knowledge/elements.md#-star-map

**Comment by Steffan153** [comment]
It looks like that's because `£` doesn't exist as an element, so it doesn't add the other one

**Comment by Steffan153** [comment]
None of the modifiers are in there, actually.
