### ISSUE TITLE
add 2-byte number compression

### ISSUE THREAD

**Issue by Vyxal-Bot-old** [Vyxal/Vyxal#887]
For example, the compressed integer 6420, `»ɾ.»`. That doens't save bytes. But if there was a monograph that took the next two or last two bytes and pushed the compressed integer, that would be useful.

(created by Steffan [here](https://chat.stackexchange.com/transcript/message/60952364))

**Comment by Steffan153** [comment]
Maybe `«` for 2-byte string compression, `»` for 2-byte number compression, `↑` for 1-byte string compression, and `↓` for 1-byte number compression?

**Comment by chunkybanana** [comment]
1-byte string and 2-byte string are already a thing.

**Comment by Steffan153** [comment]
Not 1&2-byte compression though.
