### ISSUE TITLE
`ẇ` is still still janky

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#937]
https://vyxal.pythonanywhere.com/#WyIiLCIiLCLin6hgYWJjYCB8IGBkZWZgIHwgYGhpamAgfCBga2xtYCB8IGBub3BgIOKfqSAy4bqHIiwiIiwiIl0=

And the existing PR won't fix this

**Comment by Steffan153** [comment]
The existing PR fixes it for me:

```
$ poetry run vyxal temp.vy
⟨ `abcdef` | `hijklm` | `nop` ⟩
```

**Comment by chunkybanana** [comment]
That's *not* what we want - it should behave normally on lists of strings.
