### ISSUE TITLE
SyntaxError: leading zeros in decimal integer literals are not permitted

### ISSUE THREAD

**Issue by SamMatzko** [Vyxal/Vyxal#952]
I'm trying to get the current date as a vector, so I'm using Vyxal's [`kð`](https://github.com/Vyxal/Vyxal/blob/main/documents/knowledge/elements.md#k%C3%B0-current-day-in-the-format-ddmmyyyy) constant. However, when I try to run the Vyxal program, I get an error from the interpreter:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/vyxal", line 8, in <module>
    sys.exit(cli())
  File "/home/user/.local/lib/python3.9/site-packages/vyxal/main.py", line 296, in cli
    execute_vyxal(file_name, flags, inputs)
  File "/home/user/.local/lib/python3.9/site-packages/vyxal/main.py", line 164, in execute_vyxal
    exec(code, locals() | globals())
  File "<string>", line 1, in <module>
  File "<string>", line 1
    [08,05,2022]
      ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
```
I can reproduce this error when running a simple expression in the Python interpreter:

```python
i = 01
```

So it looks like Vyxal is creating a string that will then be executed as the program, but it's putting leading zeroes on the numbers. The same error occurs with [`kN`](https://github.com/Vyxal/Vyxal/blob/main/documents/knowledge/elements.md#kn-current-time-as-a-list-of-hhmmss) as well

**Comment by cgccuser** [comment]
`datetime.strftime` unfortunately doesn't have a way to format without leading zeroes. Maybe wasn't caught because the element was written after the 10th of October, November, or December :P
