### ISSUE TITLE
`τ` returns list with string `rhs` and `lhs == 0`

### ISSUE THREAD

**Issue by Steffan153** [Vyxal/Vyxal#956]
https://vyxal.pythonanywhere.com/#WyIiLCIiLCIwIGBhc2RgIM+EIiwiIiwiIl0=

**Comment by cgccuser** [comment]
The docs say it works on numbers and strings too but it [immediately errors](https://github.com/Vyxal/Vyxal/blob/main/vyxal/elements.py#L4298) if you give it a string and number

**Comment by Steffan153** [comment]
The docs actually don't say it works with `str a, num b`, just `num a, str b`. But that should be fixed as well.

**Comment by Lyxal** [comment]
It's a feature - https://chat.stackexchange.com/transcript/106764?m=61067917#61067917
