### ISSUE TITLE
`ε` does not vectorize

### ISSUE THREAD

**Issue by Steffan153** [Vyxal/Vyxal#958]

**Comment by cgccuser** [comment]
I think the current behavior is okay, to be honest. How is the interpreter to choose which way to vectorize it?

**Comment by Lyxal** [comment]
Not-vectorising is by design, because it's really supposed to be vertical joining. The absolute value functionality was to
cover the integer-integer overload.

**Comment by Steffan153** [comment]
I guess so, but we could still have it vectorize where both sides boil down to numbers, like [this](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIkzrUiLCIiLCJbWzEsM10sIFsyXV1cbjUiXQ==). It currently errors with both arguments as numbers. Or also where the first list only has a depth of 1.
