### ISSUE TITLE
Add element to get prime factorization with exponents

### ISSUE THREAD

**Issue by Steffan153** [Vyxal/Vyxal#969]
It would be Vyxal `ǐĠv₍hL`: [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLHkMSgduKCjWhMIiwiIiwiNzIwIl0=)

We could also add one to only return the exponents.

**Comment by chunkybanana** [comment]
[`ǐĊ`](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIxMjDHkMSKIiwiIiwiIl0=)

**Comment by Steffan153** [comment]
only getting the exponents would still be four bytes: `ǐĠvL` or `ǐĊvt`.
